use std::collections::HashSet;

use crate::meta::{ClassMeta, InterfaceMeta, MethodMeta, ParamDirection};
use crate::types::TypeMeta;

use super::typescript::{
    build_method_sig, ts_dynwinrt_type, generate_interface_registration,
    trim_trailing_newline_add_semicolon, collect_used_structs_from_class,
    collect_used_structs_from_iface, collect_used_generics_from_methods,
    collect_used_generics_from_class, collect_iface_type_imports,
    get_in_params, to_camel_case, capitalize, convert_return,
    convert_array_return, wrap_arg, struct_field_getter,
    struct_field_setter, collect_type_imports,
};

// ======================================================================
// Helper: JS param list (no type annotations)
// ======================================================================

fn js_param_list(in_params: &[&crate::meta::ParamMeta]) -> String {
    in_params.iter()
        .map(|p| to_camel_case(&p.name))
        .collect::<Vec<_>>()
        .join(", ")
}

// ======================================================================
// Helper: JS wrap_arg (no `as any`)
// ======================================================================

fn js_wrap_arg(name: &str, typ: &TypeMeta) -> String {
    match typ {
        TypeMeta::RuntimeClass { .. } | TypeMeta::Object | TypeMeta::Interface { .. }
        | TypeMeta::Parameterized { .. } | TypeMeta::Delegate { .. } => {
            format!("{}._obj || {}", name, name)
        }
        _ => wrap_arg(name, typ),
    }
}

fn js_build_args_expr(in_params: &[&crate::meta::ParamMeta]) -> String {
    in_params.iter()
        .map(|p| js_wrap_arg(&to_camel_case(&p.name), &p.typ))
        .collect::<Vec<_>>()
        .join(", ")
}

// ======================================================================
// Helper: format CJS import lines
// ======================================================================

fn format_cjs_type_import(name: &str, kind: &str) -> String {
    if kind == "interface" {
        format!("const {{ IID_{name}, {name} }} = require('./{name}');\n")
    } else {
        format!("const {{ {} }} = require('./{}');\n", name, name)
    }
}

// ======================================================================
// Public: generate_index
// ======================================================================

pub fn generate_index(classes: &[ClassMeta], interfaces: &[InterfaceMeta], enums: &[TypeMeta]) -> String {
    let mut out = String::new();
    let mut exports: Vec<String> = Vec::new();

    out.push_str("// Generated by winrt-meta — do not edit\n");

    for class in classes {
        out.push_str(&format!("const {{ {} }} = require('./{}');\n", class.name, class.name));
        exports.push(class.name.clone());
    }
    for iface in interfaces {
        let is_delegate = iface.methods.iter().any(|m| m.name == ".ctor")
            && iface.methods.iter().any(|m| m.name == "Invoke");
        if is_delegate {
            out.push_str(&format!(
                "const {{ IID_{iname}, {iname}_PARAM_TYPES }} = require('./{iname}');\n",
                iname = iface.name
            ));
            exports.push(format!("IID_{}", iface.name));
            exports.push(format!("{}_PARAM_TYPES", iface.name));
        } else {
            out.push_str(&format!(
                "const {{ IID_{iname}, {iname} }} = require('./{iname}');\n",
                iname = iface.name
            ));
            exports.push(format!("IID_{}", iface.name));
            exports.push(iface.name.clone());
        }
    }
    for en in enums {
        if let TypeMeta::Enum { name, .. } = en {
            out.push_str(&format!("const {{ {} }} = require('./{}');\n", name, name));
            exports.push(name.clone());
        }
    }

    out.push_str(&format!("module.exports = {{ {} }};\n", exports.join(", ")));
    out
}

// ======================================================================
// Public: generate_enum
// ======================================================================

pub fn generate_enum(en: &TypeMeta) -> Option<String> {
    let (name, members) = match en {
        TypeMeta::Enum { name, members, .. } => (name, members),
        _ => return None,
    };

    let mut out = String::new();
    out.push_str("// Generated by winrt-meta — do not edit\n\n");
    let member_strs: Vec<String> = members.iter()
        .map(|m| format!("{}: {}", m.name, m.value))
        .collect();
    out.push_str(&format!(
        "const {} = Object.freeze({{ {} }});\n",
        name,
        member_strs.join(", ")
    ));
    out.push_str(&format!("module.exports = {{ {} }};\n", name));
    Some(out)
}

// ======================================================================
// Public: generate_interface
// ======================================================================

pub fn generate_interface(iface: &InterfaceMeta, known_types: &HashSet<String>, delegate_type_names: &HashSet<String>) -> String {
    // Detect delegate types (have .ctor + Invoke methods)
    let is_delegate = iface.methods.iter().any(|m| m.name == ".ctor")
        && iface.methods.iter().any(|m| m.name == "Invoke");
    if is_delegate {
        return generate_delegate(iface);
    }

    // Collect structs used in interface methods
    let used_structs = collect_used_structs_from_iface(iface);
    let has_structs = !used_structs.is_empty();

    let mut out = String::new();
    let mut exports: Vec<String> = Vec::new();

    out.push_str("// Generated by winrt-meta — do not edit\n");
    if has_structs {
        out.push_str("const { DynWinRtType, DynWinRtMethodSig, DynWinRtValue, DynWinRtArray, DynWinRtStruct, DynWinRtDelegate, WinGuid } = require('dynwinrt-js');\n");
    } else {
        out.push_str("const { DynWinRtType, DynWinRtMethodSig, DynWinRtValue, DynWinRtArray, DynWinRtDelegate, WinGuid } = require('dynwinrt-js');\n");
    }

    // Collect delegate names
    let mut delegate_names: HashSet<String> = delegate_type_names.clone();
    for method in &iface.methods {
        for p in &method.params {
            match &p.typ {
                TypeMeta::Delegate { name, .. } => { delegate_names.insert(name.clone()); }
                _ => {}
            }
            if method.is_event_add || method.is_event_remove || method.name.starts_with("put_") {
                if let TypeMeta::Parameterized { name, args, .. } = &p.typ {
                    delegate_names.insert(crate::meta::make_parameterized_name(name, args));
                }
            }
        }
    }

    // Import parameterized collection types (skip delegates)
    let collection_names = collect_used_generics_from_methods(&iface.methods);
    for cname in &collection_names {
        if cname != &iface.name && !delegate_names.contains(cname) {
            out.push_str(&format!("const {{ {} }} = require('./{}');\n", cname, cname));
        }
    }

    // Import delegate IID + PARAM_TYPES for event methods
    for dname in &delegate_names {
        out.push_str(&format!(
            "const {{ IID_{dname}, {dname}_PARAM_TYPES }} = require('./{dname}');\n",
        ));
    }

    // Type imports for referenced types (enums, classes, other interfaces)
    let type_imports = collect_iface_type_imports(iface);
    for (_ns, name, kind) in &type_imports {
        if known_types.contains(name) && !delegate_names.contains(name) {
            out.push_str(&format_cjs_type_import(name, kind));
        }
    }
    out.push('\n');

    // IID constant
    if let Some(ref piid) = iface.generic_piid {
        let args_ts: Vec<String> = iface.generic_args.iter().map(|a| ts_dynwinrt_type(a)).collect();
        out.push_str(&format!(
            "const IID_{} = DynWinRtType.parameterized(WinGuid.parse('{}'), [{}]).iid();\n\n",
            iface.name, piid, args_ts.join(", ")
        ));
    } else if !iface.iid.is_empty() {
        out.push_str(&format!(
            "const IID_{} = WinGuid.parse('{}');\n\n",
            iface.name, iface.iid
        ));
    }
    exports.push(format!("IID_{}", iface.name));

    // Interface registration
    out.push_str(&format!("const _{} = DynWinRtType.registerInterface(\n", iface.name));
    out.push_str(&format!("    \"{}\", IID_{})\n", iface.name, iface.name));
    for method in &iface.methods {
        out.push_str(&format!(
            "    .addMethod(\"{}\", {})\n",
            method.name,
            build_method_sig(method)
        ));
    }
    trim_trailing_newline_add_semicolon(&mut out);
    out.push('\n');

    // Struct unpack/pack helpers (no TS interface declaration)
    for s in &used_structs {
        out.push_str(&generate_js_struct_helpers(s));
        out.push('\n');
    }

    // Wrapper class
    out.push_str(&format!("class {} {{\n", iface.name));
    if iface.generic_piid.is_some() {
        out.push_str("    constructor(obj) {\n");
        out.push_str(&format!("        this._obj = obj.cast(IID_{});\n", iface.name));
        out.push_str("    }\n");
    } else {
        out.push_str("    constructor(obj) {\n");
        out.push_str("        this._obj = obj;\n");
        out.push_str("    }\n");
    }

    // static from()
    if !iface.iid.is_empty() {
        out.push('\n');
        out.push_str(&format!(
            "    static from(obj) {{\n"
        ));
        out.push_str(&format!(
            "        return new {}(obj.cast(IID_{}));\n",
            iface.name, iface.name
        ));
        out.push_str("    }\n");
    }

    // static create() for IVector<T> and IMap<K,V>
    if let Some(ref piid) = iface.generic_piid {
        if piid == "913337e9-11a1-4345-a3a2-4e7f956e222d" && iface.generic_args.len() == 1 {
            // IVector<T> — generate static create(items) factory
            let elem_type = ts_dynwinrt_type(&iface.generic_args[0]);
            out.push('\n');
            out.push_str("    /**\n");
            out.push_str("     * Create a new IVector from an array of items.\n");
            out.push_str("     * Each item must be a DynWinRtValue object.\n");
            out.push_str("     */\n");
            out.push_str(&format!(
                "    static create(items) {{\n        return new {}(DynWinRtValue.createVector(items.map(i => i._obj || i), {}));\n    }}\n",
                iface.name, elem_type
            ));
        } else if piid == "3c2925fe-8519-45c1-aa79-197b6718c1c1" && iface.generic_args.len() == 2 {
            // IMap<K,V> — generate static create(keys, values) factory
            let key_type = ts_dynwinrt_type(&iface.generic_args[0]);
            let val_type = ts_dynwinrt_type(&iface.generic_args[1]);
            out.push('\n');
            out.push_str("    /**\n");
            out.push_str("     * Create a new IMap from parallel arrays of keys and values.\n");
            out.push_str("     * Each key/value must be a DynWinRtValue object.\n");
            out.push_str("     */\n");
            out.push_str(&format!(
                "    static create(keys, values) {{\n        return new {}(DynWinRtValue.createMap(keys.map(k => k._obj || k), values.map(v => v._obj || v), {}, {}));\n    }}\n",
                iface.name, key_type, val_type
            ));
        }
    }

    // Instance methods
    let iface_var = format!("_{}", iface.name);
    for method in &iface.methods {
        out.push('\n');
        out.push_str(&generate_js_iface_instance_method(iface, &iface_var, method, known_types, delegate_type_names));
    }

    out.push_str("}\n");
    exports.push(iface.name.clone());

    out.push_str(&format!("module.exports = {{ {} }};\n", exports.join(", ")));
    out
}

// ======================================================================
// Public: generate_class
// ======================================================================

pub fn generate_class(class: &ClassMeta, known_types: &HashSet<String>, delegate_type_names: &HashSet<String>) -> String {
    let used_structs = collect_used_structs_from_class(class);
    let has_structs = !used_structs.is_empty();

    let mut out = String::new();
    let mut exports: Vec<String> = Vec::new();

    // Header
    out.push_str("// Generated by winrt-meta — do not edit\n");
    if has_structs {
        out.push_str("const { DynWinRtType, DynWinRtMethodSig, DynWinRtValue, DynWinRtArray, DynWinRtStruct, DynWinRtDelegate, WinGuid } = require('dynwinrt-js');\n");
    } else {
        out.push_str("const { DynWinRtType, DynWinRtMethodSig, DynWinRtValue, DynWinRtArray, DynWinRtDelegate, WinGuid } = require('dynwinrt-js');\n");
    }

    // IActivationFactory for default constructor (ActivateInstance at vtable index 6)
    if class.has_default_constructor {
        out.push_str("const _IActivationFactory = DynWinRtType.registerInterface('IActivationFactory', WinGuid.parse('00000035-0000-0000-c000-000000000046'))\n    .addMethod('ActivateInstance', new DynWinRtMethodSig().addOut(DynWinRtType.object()));\n");
    }

    // Collect delegate names from all interfaces of this class
    let mut delegate_names: HashSet<String> = delegate_type_names.clone();
    let all_ifaces: Vec<&InterfaceMeta> = class.default_interface.iter()
        .chain(class.factory_interfaces.iter())
        .chain(class.static_interfaces.iter())
        .chain(class.required_interfaces.iter())
        .collect();
    for iface in &all_ifaces {
        for method in &iface.methods {
            for p in &method.params {
                match &p.typ {
                    TypeMeta::Delegate { name, .. } => { delegate_names.insert(name.clone()); }
                    _ => {}
                }
                if method.is_event_add || method.is_event_remove || method.name.starts_with("put_") {
                    if let TypeMeta::Parameterized { name, args, .. } = &p.typ {
                        delegate_names.insert(crate::meta::make_parameterized_name(name, args));
                    }
                }
            }
        }
    }

    // Collection generics import (skip delegates)
    let collection_names = collect_used_generics_from_class(class);
    for cname in &collection_names {
        if !delegate_names.contains(cname) {
            out.push_str(&format!("const {{ {} }} = require('./{}');\n", cname, cname));
        }
    }

    // Import delegate IID + PARAM_TYPES for event methods
    for dname in &delegate_names {
        out.push_str(&format!(
            "const {{ IID_{dname}, {dname}_PARAM_TYPES }} = require('./{dname}');\n",
        ));
    }

    // Type imports — only for types that have generated files (skip delegates)
    // Track ALL imported names to avoid redeclaring them as local constants
    let mut imported_names: HashSet<String> = HashSet::new();
    let imports = collect_type_imports(class);
    for (_ns, name, kind) in &imports {
        if known_types.contains(name) && !delegate_names.contains(name) {
            out.push_str(&format_cjs_type_import(name, kind));
            imported_names.insert(name.clone());
            if kind == "interface" {
                imported_names.insert(format!("IID_{}", name));
            }
        }
    }
    out.push('\n');

    // IID constants for all interfaces used by this class (skip if already imported)
    let all_class_ifaces: Vec<&InterfaceMeta> = class.default_interface.iter()
        .chain(class.factory_interfaces.iter())
        .chain(class.static_interfaces.iter())
        .chain(class.required_interfaces.iter())
        .collect();
    for iface in &all_class_ifaces {
        let iid_name = format!("IID_{}", iface.name);
        if !iface.iid.is_empty() && !imported_names.contains(&iid_name) {
            out.push_str(&format!(
                "const {} = WinGuid.parse('{}');\n",
                iid_name, iface.iid
            ));
        }
    }
    out.push('\n');

    // Interface registrations — ALL use _ prefix in JS to avoid conflicts with imports
    if let Some(ref iface) = class.default_interface {
        let mut reg = generate_interface_registration(iface);
        reg = reg.replacen(&format!("const {} =", iface.name), &format!("const _{} =", iface.name), 1);
        out.push_str(&reg);
        out.push('\n');
    }
    for iface in &class.factory_interfaces {
        let mut reg = generate_interface_registration(iface);
        reg = reg.replacen(&format!("const {} =", iface.name), &format!("const _{} =", iface.name), 1);
        out.push_str(&reg);
        out.push('\n');
    }
    for iface in &class.static_interfaces {
        let mut reg = generate_interface_registration(iface);
        reg = reg.replacen(&format!("const {} =", iface.name), &format!("const _{} =", iface.name), 1);
        out.push_str(&reg);
        out.push('\n');
    }
    for iface in &class.required_interfaces {
        let mut reg = generate_interface_registration(iface);
        reg = reg.replacen(&format!("const {} =", iface.name), &format!("const _{} =", iface.name), 1);
        out.push_str(&reg);
        out.push('\n');
    }

    // Struct unpack/pack helpers (no TS interface)
    for s in &used_structs {
        out.push_str(&generate_js_struct_helpers(s));
        out.push('\n');
    }

    // Class declaration
    out.push_str(&format!("class {} {{\n", class.name));
    exports.push(class.name.clone());

    // Lazy-cached factory/static interface accessors
    let mut declared: HashSet<String> = HashSet::new();
    for iface in &class.factory_interfaces {
        let key = format!("f_{}", iface.name);
        if !iface.iid.is_empty() && declared.insert(key.clone()) {
            out.push_str(&format!("    static _{k};\n", k = key));
            out.push_str(&format!(
                "    static {k}() {{ return {cls}._{k} ??= DynWinRtValue.activationFactory('{full}').cast(IID_{iface}); }}\n",
                k = key, cls = class.name, iface = iface.name, full = class.full_name
            ));
        }
    }
    for iface in &class.static_interfaces {
        let key = format!("s_{}", iface.name);
        if !iface.iid.is_empty() && declared.insert(key.clone()) {
            out.push_str(&format!("    static _{k};\n", k = key));
            out.push_str(&format!(
                "    static {k}() {{ return {cls}._{k} ??= DynWinRtValue.activationFactory('{full}').cast(IID_{iface}); }}\n",
                k = key, cls = class.name, iface = iface.name, full = class.full_name
            ));
        }
    }

    out.push('\n');
    out.push_str("    constructor(obj) {\n");
    out.push_str("        this._obj = obj;\n");
    out.push_str("    }\n");

    // Default constructor — use IActivationFactory.ActivateInstance (vtable index 6)
    if class.has_default_constructor {
        let has_create_factory = class.factory_interfaces.iter()
            .any(|iface| iface.methods.iter().any(|m| {
                let camel = to_camel_case(&m.name);
                camel == "create" || camel.starts_with("create")
            }));
        let ctor_name = if has_create_factory { "createDefault" } else { "create" };
        out.push('\n');
        out.push_str(&format!(
            "    static {}() {{\n",
            ctor_name
        ));
        out.push_str(&format!(
            "        return new {}(_IActivationFactory.method(6).invoke(DynWinRtValue.activationFactory('{}'), []));\n",
            class.name, class.full_name
        ));
        out.push_str("    }\n");
    }

    // Factory methods
    for iface in &class.factory_interfaces {
        for method in &iface.methods {
            out.push('\n');
            out.push_str(&generate_js_factory_method_invoke(class, iface, method));
        }
    }

    // Static methods
    for iface in &class.static_interfaces {
        for method in &iface.methods {
            out.push('\n');
            out.push_str(&generate_js_static_method_invoke(class, iface, method, known_types));
        }
    }

    // Instance methods (default interface)
    if let Some(ref default_iface) = class.default_interface {
        let iface_var = format!("_{}", default_iface.name);
        for method in &default_iface.methods {
            out.push('\n');
            out.push_str(&generate_js_iface_instance_method(default_iface, &iface_var, method, known_types, delegate_type_names));
        }
    }

    // .as() method
    if !class.required_interfaces.is_empty() {
        out.push('\n');
        out.push_str("    as(InterfaceClass) {\n");
        out.push_str("        return InterfaceClass.from(this._obj);\n");
        out.push_str("    }\n");
    }

    out.push_str("}\n");

    // Required interface wrapper classes — skip if already imported (avoids redeclaration)
    for req_iface in &class.required_interfaces {
        if req_iface.iid.is_empty() { continue; }
        if imported_names.contains(&req_iface.name) {
            // Already imported from its own file — just re-export it
            exports.push(req_iface.name.clone());
            continue;
        }
        let reg_var = format!("_{}", req_iface.name);
        out.push('\n');
        out.push_str(&format!("class {} {{\n", req_iface.name));
        exports.push(req_iface.name.clone());
        out.push_str("    constructor(obj) {\n");
        out.push_str("        this._obj = obj;\n");
        out.push_str("    }\n\n");
        out.push_str(&format!(
            "    static from(obj) {{\n"
        ));
        out.push_str(&format!(
            "        return new {}(obj.cast(IID_{}));\n",
            req_iface.name, req_iface.name
        ));
        out.push_str("    }\n");
        for method in &req_iface.methods {
            out.push('\n');
            out.push_str(&generate_js_iface_instance_method(req_iface, &reg_var, method, known_types, delegate_type_names));
        }
        out.push_str("}\n");
    }

    out.push_str(&format!("module.exports = {{ {} }};\n", exports.join(", ")));
    out
}

// ======================================================================
// Private: generate_delegate (CJS version)
// ======================================================================

fn generate_delegate(iface: &InterfaceMeta) -> String {
    let mut out = String::new();
    let mut exports: Vec<String> = Vec::new();

    out.push_str("// Generated by winrt-meta — do not edit (delegate)\n");
    out.push_str("const { DynWinRtType, WinGuid } = require('dynwinrt-js');\n\n");

    let invoke = iface.methods.iter().find(|m| m.name == "Invoke");
    let param_exprs: Vec<String> = invoke.map(|inv| {
        inv.params.iter()
            .filter(|p| p.direction == ParamDirection::In)
            .map(|p| ts_dynwinrt_type(&p.typ))
            .collect()
    }).unwrap_or_default();

    if !iface.iid.is_empty() {
        out.push_str(&format!(
            "const IID_{} = DynWinRtType.parameterized(WinGuid.parse('{}'), [{}]).iid();\n",
            iface.name, iface.iid, param_exprs.join(", ")
        ));
    } else {
        out.push_str(&format!(
            "const IID_{} = undefined;\n",
            iface.name
        ));
    }
    exports.push(format!("IID_{}", iface.name));

    let invoke = iface.methods.iter().find(|m| m.name == "Invoke");
    if let Some(invoke) = invoke {
        let param_exprs: Vec<String> = invoke.params.iter()
            .filter(|p| p.direction == ParamDirection::In)
            .map(|p| ts_dynwinrt_type(&p.typ))
            .collect();
        out.push_str(&format!(
            "const {}_PARAM_TYPES = [{}];\n",
            iface.name,
            param_exprs.join(", ")
        ));
        exports.push(format!("{}_PARAM_TYPES", iface.name));
    }

    out.push_str(&format!("module.exports = {{ {} }};\n", exports.join(", ")));
    out
}

// ======================================================================
// Private: struct helpers (JS version — no TS interface)
// ======================================================================

fn generate_js_struct_helpers(s: &TypeMeta) -> String {
    let (namespace, name, fields) = match s {
        TypeMeta::Struct { namespace, name, fields } => (namespace, name, fields),
        _ => return String::new(),
    };
    let mut out = String::new();

    // No TS interface declaration — skip it

    // _unpack function (no type annotations)
    out.push_str(&format!("function _unpack{}(v) {{\n", name));
    out.push_str("    const s = v.asStruct();\n");
    out.push_str("    return { ");
    let field_exprs: Vec<String> = fields.iter().enumerate().map(|(i, f)| {
        format!("{}: {}", to_camel_case(&f.name), struct_field_getter(&f.typ, i))
    }).collect();
    out.push_str(&field_exprs.join(", "));
    out.push_str(" };\n");
    out.push_str("}\n");

    // Type constant for _pack
    let full_name = format!("{}.{}", namespace, name);
    let field_types: Vec<String> = fields.iter().map(|f| ts_dynwinrt_type(&f.typ)).collect();
    out.push_str(&format!("const _{}_Type = DynWinRtType.structType('{}', [{}]);\n",
        name, full_name, field_types.join(", ")));

    // _pack function (no type annotations)
    out.push_str(&format!("function _pack{}(v) {{\n", name));
    out.push_str(&format!("    const s = DynWinRtStruct.create(_{}_Type);\n", name));
    for (i, f) in fields.iter().enumerate() {
        out.push_str(&format!("    {};\n", struct_field_setter(&f.typ, i, &format!("v.{}", to_camel_case(&f.name)))));
    }
    out.push_str("    return s;\n");
    out.push_str("}\n");

    out
}

// ======================================================================
// Private: factory method invoke (JS version)
// ======================================================================

fn generate_js_factory_method_invoke(
    class: &ClassMeta,
    iface: &InterfaceMeta,
    method: &MethodMeta,
) -> String {
    let in_params = get_in_params(method);
    let js_params = js_param_list(&in_params);

    let is_async = method.return_type.as_ref().is_some_and(|rt| rt.is_async());

    let mut out = String::new();
    let async_kw = if is_async { "async " } else { "" };
    out.push_str(&format!(
        "    static {}{}({}) {{\n",
        async_kw, to_camel_case(&method.name), js_params
    ));

    let args_expr = js_build_args_expr(&in_params);
    let invoke_expr = format!(
        "_{iface}.method({idx}).invoke({cls}.f_{iface}(), [{args}])",
        iface = iface.name, idx = method.vtable_index, cls = class.name, args = args_expr
    );

    if is_async {
        out.push_str(&format!(
            "        return new {}(await {}.toPromise());\n",
            class.name, invoke_expr
        ));
    } else {
        out.push_str(&format!(
            "        return new {}({});\n",
            class.name, invoke_expr
        ));
    }
    out.push_str("    }\n");
    out
}

// ======================================================================
// Private: static method invoke (JS version)
// ======================================================================

fn generate_js_static_method_invoke(
    class: &ClassMeta,
    iface: &InterfaceMeta,
    method: &MethodMeta,
    known_types: &HashSet<String>,
) -> String {
    let in_params = get_in_params(method);
    let js_params = js_param_list(&in_params);

    let return_type = method.return_type.as_ref();
    let is_async = return_type.is_some_and(|rt| rt.is_async());

    let mut out = String::new();
    let statics_call = format!("{cls}.s_{iface}()", cls = class.name, iface = iface.name);

    // Static property getter
    if method.is_property_getter && in_params.is_empty() {
        let prop_name = to_camel_case(method.name.strip_prefix("get_").unwrap_or(&method.name));
        out.push_str(&format!("    static get {}() {{\n", prop_name));
        let invoke_expr = format!(
            "_{}.method({}).invoke({}, [])",
            iface.name, method.vtable_index, statics_call
        );
        let converted = convert_return(&invoke_expr, return_type, false, known_types);
        out.push_str(&format!("        return {};\n", converted));
        out.push_str("    }\n");
    } else {
        let async_kw = if is_async { "async " } else { "" };
        out.push_str(&format!(
            "    static {}{}({}) {{\n",
            async_kw, to_camel_case(&method.name), js_params
        ));
        let args_expr = js_build_args_expr(&in_params);
        let invoke_expr = format!(
            "_{}.method({}).invoke({}, [{}])",
            iface.name, method.vtable_index, statics_call, args_expr
        );
        let converted = convert_return(&invoke_expr, return_type, is_async, known_types);
        out.push_str(&format!("        return {};\n", converted));
        out.push_str("    }\n");
    }
    out
}

// ======================================================================
// Private: instance method (JS version)
// ======================================================================

fn generate_js_iface_instance_method(
    _iface: &InterfaceMeta,
    iface_var: &str,
    method: &MethodMeta,
    known_types: &HashSet<String>,
    delegate_type_names: &HashSet<String>,
) -> String {
    generate_js_method_body(iface_var, "this._obj", method, known_types, delegate_type_names, None)
}

fn generate_js_method_body(
    iface_var: &str,
    obj_expr: &str,
    method: &MethodMeta,
    known_types: &HashSet<String>,
    delegate_type_names: &HashSet<String>,
    js_name_override: Option<&str>,
) -> String {
    let in_params = get_in_params(method);
    let return_type = method.return_type.as_ref();
    let is_async = return_type.is_some_and(|rt| rt.is_async());
    let has_array_out = method.params.iter().any(|p| {
        (p.direction == ParamDirection::Out || p.direction == ParamDirection::OutFill)
            && matches!(p.typ, TypeMeta::Array(_))
    });
    let has_return = return_type.is_some() || has_array_out;

    let mut out = String::new();

    // Event add
    if method.is_event_add {
        let event_name = to_camel_case(method.name.strip_prefix("add_").unwrap_or(&method.name));
        let delegate_name = in_params.first().and_then(|p| match &p.typ {
            TypeMeta::Parameterized { name, args, .. } =>
                Some(crate::meta::make_parameterized_name(name, args)),
            TypeMeta::Delegate { name, .. } => Some(name.clone()),
            _ => None,
        });
        out.push_str(&format!(
            "    on{}(callback) {{\n",
            capitalize(&event_name)
        ));
        if let Some(ref dname) = delegate_name {
            out.push_str(&format!(
                "        const handler = DynWinRtDelegate.create(IID_{}, {}_PARAM_TYPES, callback);\n",
                dname, dname
            ));
        } else {
            out.push_str(
                "        const handler = DynWinRtDelegate.create(DynWinRtType.object().iid(), [DynWinRtType.object(), DynWinRtType.object()], callback);\n"
            );
        }
        out.push_str(&format!(
            "        return {}.method({}).invoke({}, [handler.toValue()]);\n",
            iface_var, method.vtable_index, obj_expr
        ));
        out.push_str("    }\n");
        return out;
    }
    // Event remove
    if method.is_event_remove {
        let event_name = to_camel_case(method.name.strip_prefix("remove_").unwrap_or(&method.name));
        out.push_str(&format!(
            "    off{}(token) {{\n",
            capitalize(&event_name)
        ));
        out.push_str(&format!(
            "        {}.method({}).invoke({}, [token]);\n",
            iface_var, method.vtable_index, obj_expr
        ));
        out.push_str("    }\n");
        return out;
    }

    // Helper: check if a type refers to a delegate
    let is_delegate_type = |typ: Option<&TypeMeta>| -> bool {
        match typ {
            Some(TypeMeta::Delegate { .. }) => true,
            Some(TypeMeta::Interface { name, .. }) => delegate_type_names.contains(name),
            _ => false,
        }
    };

    if method.is_property_getter && in_params.is_empty() {
        // Property getter (no return type annotation)
        let prop_name = to_camel_case(method.name.strip_prefix("get_").unwrap_or(&method.name));
        out.push_str(&format!("    get {}() {{\n", prop_name));
        let invoke_expr = format!(
            "{}.method({}).invoke({}, [])",
            iface_var, method.vtable_index, obj_expr
        );
        let converted = if is_delegate_type(return_type) {
            invoke_expr.clone()
        } else {
            convert_return(&invoke_expr, return_type, false, known_types)
        };
        out.push_str(&format!("        return {};\n", converted));
        out.push_str("    }\n");
    } else if method.is_property_setter {
        // Property setter (no param type annotation)
        let prop_name = to_camel_case(method.name.strip_prefix("put_").unwrap_or(&method.name));
        out.push_str(&format!("    set {}(value) {{\n", prop_name));
        let arg = in_params.first()
            .map(|p| js_wrap_arg("value", &p.typ))
            .unwrap_or_else(|| "value".to_string());
        out.push_str(&format!(
            "        {}.method({}).invoke({}, [{}]);\n",
            iface_var, method.vtable_index, obj_expr, arg
        ));
        out.push_str("    }\n");
    } else {
        // Regular method (no type annotations)
        let js_params = js_param_list(&in_params);
        let array_out_elem = if has_array_out && return_type.is_none() {
            method.params.iter().find_map(|p| {
                if p.direction == ParamDirection::Out || p.direction == ParamDirection::OutFill {
                    if let TypeMeta::Array(inner) = &p.typ { Some(inner.as_ref()) } else { None }
                } else { None }
            })
        } else { None };
        let method_name = js_name_override.map(|s| s.to_string()).unwrap_or_else(|| to_camel_case(&method.name));
        let async_kw = if is_async { "async " } else { "" };

        out.push_str(&format!(
            "    {}{}({}) {{\n",
            async_kw, method_name, js_params
        ));

        let args_expr = js_build_args_expr(&in_params);
        let invoke_expr = format!(
            "{}.method({}).invoke({}, [{}])",
            iface_var, method.vtable_index, obj_expr, args_expr
        );

        if !has_return && !is_async {
            out.push_str(&format!("        {};\n", invoke_expr));
        } else if let Some(elem) = array_out_elem {
            let arr_expr = format!("{}.asArray()", invoke_expr);
            let converted = convert_array_return(&arr_expr, elem, known_types);
            out.push_str(&format!("        return {};\n", converted));
        } else {
            let converted = convert_return(&invoke_expr, return_type, is_async, known_types);
            out.push_str(&format!("        return {};\n", converted));
        }
        out.push_str("    }\n");
    }

    out
}
