use std::collections::HashSet;
use std::sync::LazyLock;

use crate::meta::{ClassMeta, InterfaceMeta, MethodMeta, ParamDirection};
use crate::types::TypeMeta;

use super::typescript::{
    build_method_sig, ts_dynwinrt_type, generate_interface_registration,
    trim_trailing_newline_add_semicolon, collect_used_structs_from_class,
    collect_used_structs_from_iface, collect_used_generics_from_methods,
    collect_used_generics_from_class, collect_iface_type_imports,
    get_in_params, to_camel_case, capitalize, convert_return,
    convert_array_return, wrap_arg, struct_field_getter,
    struct_field_setter, collect_type_imports,
};

/// Empty deferred set — ESM live bindings handle circular deps natively.
static NO_DEFERRED: LazyLock<HashSet<String>> = LazyLock::new(HashSet::new);

// ======================================================================
// Helper: JS param list (no type annotations)
// ======================================================================

fn js_param_list(in_params: &[&crate::meta::ParamMeta]) -> String {
    in_params.iter()
        .map(|p| to_camel_case(&p.name))
        .collect::<Vec<_>>()
        .join(", ")
}

// ======================================================================
// Helper: JS wrap_arg (no `as any`)
// ======================================================================

fn js_wrap_arg(name: &str, typ: &TypeMeta) -> String {
    match typ {
        TypeMeta::RuntimeClass { .. } | TypeMeta::Object | TypeMeta::Interface { .. }
        | TypeMeta::Parameterized { .. } | TypeMeta::Delegate { .. } => {
            format!("{}._obj || {}", name, name)
        }
        _ => wrap_arg(name, typ),
    }
}

fn js_build_args_expr(in_params: &[&crate::meta::ParamMeta]) -> String {
    in_params.iter()
        .map(|p| js_wrap_arg(&to_camel_case(&p.name), &p.typ))
        .collect::<Vec<_>>()
        .join(", ")
}

// ======================================================================
// Helper: format ESM import line
// ======================================================================

fn format_esm_import(name: &str, kind: &str) -> String {
    if kind == "interface" {
        format!("import {{ IID_{name}, {name} }} from './{name}.mjs';\n")
    } else {
        format!("import {{ {name} }} from './{name}.mjs';\n")
    }
}

// ======================================================================
// Helper: struct export names
// ======================================================================

fn js_struct_export_names(s: &TypeMeta) -> Vec<String> {
    match s {
        TypeMeta::Struct { name, .. } => vec![
            format!("{}_Type", name),
            format!("pack{}", name),
            format!("unpack{}", name),
        ],
        _ => vec![],
    }
}

// ======================================================================
// Public: generate_index
// ======================================================================

pub fn generate_index(classes: &[ClassMeta], interfaces: &[InterfaceMeta], enums: &[TypeMeta]) -> String {
    let mut out = String::new();
    let mut seen: HashSet<String> = HashSet::new();

    out.push_str("// Generated by winrt-meta — do not edit\n");

    let mut sorted_classes: Vec<_> = classes.iter().collect();
    sorted_classes.sort_by(|a, b| a.name.cmp(&b.name));
    for class in sorted_classes {
        if !seen.insert(class.name.clone()) { continue; }
        let struct_names: Vec<_> = collect_used_structs_from_class(class).iter()
            .flat_map(|s| js_struct_export_names(s))
            .filter(|n| seen.insert(n.clone()))
            .collect();
        if struct_names.is_empty() {
            out.push_str(&format!("export {{ {} }} from './{}.mjs';\n", class.name, class.name));
        } else {
            out.push_str(&format!("export {{ {}, {} }} from './{}.mjs';\n", class.name, struct_names.join(", "), class.name));
        }
    }
    let mut sorted_ifaces: Vec<_> = interfaces.iter().collect();
    sorted_ifaces.sort_by(|a, b| a.name.cmp(&b.name));
    for iface in sorted_ifaces {
        if !seen.insert(iface.name.clone()) { continue; }
        let is_delegate = iface.methods.iter().any(|m| m.name == ".ctor")
            && iface.methods.iter().any(|m| m.name == "Invoke");
        let struct_names: Vec<_> = collect_used_structs_from_iface(iface).iter()
            .flat_map(|s| js_struct_export_names(s))
            .filter(|n| seen.insert(n.clone()))
            .collect();
        if is_delegate {
            out.push_str(&format!(
                "export {{ IID_{iname}, {iname}_PARAM_TYPES }} from './{iname}.mjs';\n",
                iname = iface.name
            ));
        } else {
            if struct_names.is_empty() {
                out.push_str(&format!(
                    "export {{ IID_{iname}, {iname} }} from './{iname}.mjs';\n",
                    iname = iface.name
                ));
            } else {
                out.push_str(&format!(
                    "export {{ IID_{iname}, {iname}, {structs} }} from './{iname}.mjs';\n",
                    iname = iface.name, structs = struct_names.join(", ")
                ));
            }
        }
    }
    let mut sorted_enums: Vec<_> = enums.iter().collect();
    sorted_enums.sort_by(|a, b| {
        let name_a = match a { TypeMeta::Enum { name, .. } => name.as_str(), _ => "" };
        let name_b = match b { TypeMeta::Enum { name, .. } => name.as_str(), _ => "" };
        name_a.cmp(name_b)
    });
    for en in sorted_enums {
        if let TypeMeta::Enum { name, .. } = en {
            if !seen.insert(name.clone()) { continue; }
            out.push_str(&format!("export {{ {} }} from './{}.mjs';\n", name, name));
        }
    }

    out
}

// ======================================================================
// Public: append_to_index — merge new types into an existing ESM index
// ======================================================================

pub fn append_to_index(
    existing: &str,
    classes: &[ClassMeta],
    interfaces: &[InterfaceMeta],
    enums: &[TypeMeta],
) -> String {
    // Parse existing export lines to find already-exported names and modules
    let mut seen: HashSet<String> = HashSet::new();
    let mut exported_modules: HashSet<String> = HashSet::new();
    for line in existing.lines() {
        if line.starts_with("export {") {
            if let Some(start) = line.find('{') {
                if let Some(end) = line.find('}') {
                    for name in line[start + 1..end].split(',') {
                        let name = name.trim();
                        if !name.is_empty() {
                            seen.insert(name.to_string());
                        }
                    }
                }
            }
            // Track module name from `from './Foo.mjs'`
            if let Some(start) = line.find("from './") {
                if let Some(end) = line[start + 8..].find(".mjs'") {
                    exported_modules.insert(line[start + 8..start + 8 + end].to_string());
                }
            }
        }
    }

    let mut out = existing.to_string();
    if !out.ends_with('\n') {
        out.push('\n');
    }

    // Add new classes
    let mut sorted_classes: Vec<_> = classes.iter().collect();
    sorted_classes.sort_by(|a, b| a.name.cmp(&b.name));
    for class in sorted_classes {
        if !exported_modules.contains(&class.name) && seen.insert(class.name.clone()) {
            let struct_names: Vec<_> = collect_used_structs_from_class(class).iter()
                .flat_map(|s| js_struct_export_names(s))
                .filter(|n| seen.insert(n.clone()))
                .collect();
            if struct_names.is_empty() {
                out.push_str(&format!("export {{ {} }} from './{}.mjs';\n", class.name, class.name));
            } else {
                out.push_str(&format!("export {{ {}, {} }} from './{}.mjs';\n", class.name, struct_names.join(", "), class.name));
            }
        }
    }

    // Add new interfaces
    let mut sorted_ifaces: Vec<_> = interfaces.iter().collect();
    sorted_ifaces.sort_by(|a, b| a.name.cmp(&b.name));
    for iface in sorted_ifaces {
        if exported_modules.contains(&iface.name) || !seen.insert(iface.name.clone()) { continue; }
        let is_delegate = iface.methods.iter().any(|m| m.name == ".ctor")
            && iface.methods.iter().any(|m| m.name == "Invoke");
        let struct_names: Vec<_> = collect_used_structs_from_iface(iface).iter()
            .flat_map(|s| js_struct_export_names(s))
            .filter(|n| seen.insert(n.clone()))
            .collect();
        if is_delegate {
            out.push_str(&format!(
                "export {{ IID_{0}, {0}_PARAM_TYPES }} from './{0}.mjs';\n",
                iface.name
            ));
        } else {
            if struct_names.is_empty() {
                out.push_str(&format!(
                    "export {{ IID_{0}, {0} }} from './{0}.mjs';\n",
                    iface.name
                ));
            } else {
                out.push_str(&format!(
                    "export {{ IID_{0}, {0}, {1} }} from './{0}.mjs';\n",
                    iface.name, struct_names.join(", ")
                ));
            }
        }
    }

    // Add new enums
    let mut sorted_enums: Vec<_> = enums.iter().collect();
    sorted_enums.sort_by(|a, b| {
        let name_a = match a { TypeMeta::Enum { name, .. } => name.as_str(), _ => "" };
        let name_b = match b { TypeMeta::Enum { name, .. } => name.as_str(), _ => "" };
        name_a.cmp(name_b)
    });
    for en in sorted_enums {
        if let TypeMeta::Enum { name, .. } = en {
            if !exported_modules.contains(name) && seen.insert(name.clone()) {
                out.push_str(&format!("export {{ {} }} from './{}.mjs';\n", name, name));
            }
        }
    }

    out
}

// ======================================================================
// Public: generate_enum
// ======================================================================

pub fn generate_enum(en: &TypeMeta) -> Option<String> {
    let (name, members) = match en {
        TypeMeta::Enum { name, members, .. } => (name, members),
        _ => return None,
    };

    let mut out = String::new();
    out.push_str("// Generated by winrt-meta — do not edit\n\n");
    let member_strs: Vec<String> = members.iter()
        .map(|m| format!("{}: {}", m.name, m.value))
        .collect();
    out.push_str(&format!(
        "export const {} = Object.freeze({{ {} }});\n",
        name,
        member_strs.join(", ")
    ));
    Some(out)
}

// ======================================================================
// Public: generate_interface
// ======================================================================

pub fn generate_interface(iface: &InterfaceMeta, known_types: &HashSet<String>, delegate_type_names: &HashSet<String>) -> String {
    // Detect delegate types (have .ctor + Invoke methods)
    let is_delegate = iface.methods.iter().any(|m| m.name == ".ctor")
        && iface.methods.iter().any(|m| m.name == "Invoke");
    if is_delegate {
        return generate_delegate(iface);
    }

    // Collect structs used in interface methods
    let used_structs = collect_used_structs_from_iface(iface);

    let mut out = String::new();

    out.push_str("// Generated by winrt-meta — do not edit\n");
    out.push_str("import { createRequire } from 'node:module';\nconst require = createRequire(import.meta.url);\nconst { DynWinRtType, DynWinRtMethodSig, DynWinRtValue, DynWinRtArray, DynWinRtStruct, DynWinRtDelegate, WinGuid } = require('dynwinrt-js');\n");

    // Collect delegate names
    let mut delegate_names: HashSet<String> = delegate_type_names.clone();
    for method in &iface.methods {
        for p in &method.params {
            match &p.typ {
                TypeMeta::Delegate { name, .. } => { delegate_names.insert(name.clone()); }
                _ => {}
            }
            if method.is_event_add || method.is_event_remove || method.name.starts_with("put_") {
                if let TypeMeta::Parameterized { name, args, .. } = &p.typ {
                    delegate_names.insert(crate::meta::make_parameterized_name(name, args));
                }
            }
        }
    }

    // Import parameterized collection types (direct import — ESM handles circular deps)
    let collection_names = collect_used_generics_from_methods(&iface.methods);
    for cname in &collection_names {
        if cname != &iface.name && !delegate_names.contains(cname) {
            out.push_str(&format!("import {{ {} }} from './{}.mjs';\n", cname, cname));
        }
    }

    // Import delegate IID + PARAM_TYPES for event methods
    let mut sorted_delegates: Vec<_> = delegate_names.iter().collect();
    sorted_delegates.sort();
    for dname in &sorted_delegates {
        out.push_str(&format!(
            "import {{ IID_{dname}, {dname}_PARAM_TYPES }} from './{dname}.mjs';\n",
        ));
    }

    // Type imports for referenced types (direct import)
    let type_imports = collect_iface_type_imports(iface);
    let mut sorted_type_imports: Vec<_> = type_imports.iter().collect();
    sorted_type_imports.sort();
    for (_ns, name, kind) in &sorted_type_imports {
        if known_types.contains(name) && !delegate_names.contains(name) {
            out.push_str(&format_esm_import(name, kind));
        }
    }
    out.push('\n');

    // IID constant
    if let Some(ref piid) = iface.generic_piid {
        let args_ts: Vec<String> = iface.generic_args.iter().map(|a| ts_dynwinrt_type(a)).collect();
        out.push_str(&format!(
            "export const IID_{} = DynWinRtType.parameterized(WinGuid.parse('{}'), [{}]).iid();\n\n",
            iface.name, piid, args_ts.join(", ")
        ));
    } else if !iface.iid.is_empty() {
        out.push_str(&format!(
            "export const IID_{} = WinGuid.parse('{}');\n\n",
            iface.name, iface.iid
        ));
    }

    // Interface registration
    out.push_str(&format!("const _{} = DynWinRtType.registerInterface(\n", iface.name));
    out.push_str(&format!("    \"{}\", IID_{})\n", iface.name, iface.name));
    for method in &iface.methods {
        out.push_str(&format!(
            "    .addMethod(\"{}\", {})\n",
            method.name,
            build_method_sig(method)
        ));
    }
    trim_trailing_newline_add_semicolon(&mut out);
    out.push('\n');

    // Struct helpers
    for s in &used_structs {
        out.push_str(&generate_esm_struct_helpers(s));
        out.push('\n');
    }

    // Wrapper class
    out.push_str(&format!("export class {} {{\n", iface.name));
    if iface.generic_piid.is_some() {
        out.push_str("    constructor(obj) {\n");
        out.push_str(&format!("        this._obj = obj.cast(IID_{});\n", iface.name));
        out.push_str("    }\n");
    } else {
        out.push_str("    constructor(obj) {\n");
        out.push_str("        this._obj = obj;\n");
        out.push_str("    }\n");
    }

    // static from()
    if !iface.iid.is_empty() {
        out.push('\n');
        out.push_str("    static from(obj) {\n");
        out.push_str(&format!(
            "        return new {}(obj.cast(IID_{}));\n",
            iface.name, iface.name
        ));
        out.push_str("    }\n");
    }

    // static create() for IVector<T> and IMap<K,V>
    if let Some(ref piid) = iface.generic_piid {
        if piid == "913337e9-11a1-4345-a3a2-4e7f956e222d" && iface.generic_args.len() == 1 {
            let elem_type = ts_dynwinrt_type(&iface.generic_args[0]);
            out.push('\n');
            out.push_str(&format!(
                "    static create(items) {{\n        return new {}(DynWinRtValue.createVector(items.map(i => i._obj || i), {}));\n    }}\n",
                iface.name, elem_type
            ));
        } else if piid == "3c2925fe-8519-45c1-aa79-197b6718c1c1" && iface.generic_args.len() == 2 {
            let key_type = ts_dynwinrt_type(&iface.generic_args[0]);
            let val_type = ts_dynwinrt_type(&iface.generic_args[1]);
            out.push('\n');
            out.push_str(&format!(
                "    static create(keys, values) {{\n        return new {}(DynWinRtValue.createMap(keys.map(k => k._obj || k), values.map(v => v._obj || v), {}, {}));\n    }}\n",
                iface.name, key_type, val_type
            ));
        }
    }

    // Instance methods
    let iface_var = format!("_{}", iface.name);
    for method in &iface.methods {
        out.push('\n');
        out.push_str(&generate_instance_method(iface, &iface_var, method, known_types, delegate_type_names));
    }

    out.push_str("}\n");

    out
}

// ======================================================================
// Public: generate_class
// ======================================================================

pub fn generate_class(class: &ClassMeta, known_types: &HashSet<String>, delegate_type_names: &HashSet<String>, shared_iids: &HashSet<String>) -> String {
    let used_structs = collect_used_structs_from_class(class);

    let mut out = String::new();

    // Header
    out.push_str("// Generated by winrt-meta — do not edit\n");
    out.push_str("import { createRequire } from 'node:module';\nconst require = createRequire(import.meta.url);\nconst { DynWinRtType, DynWinRtMethodSig, DynWinRtValue, DynWinRtArray, DynWinRtStruct, DynWinRtDelegate, WinGuid } = require('dynwinrt-js');\n");

    // IActivationFactory for default constructor
    if class.has_default_constructor {
        out.push_str("const _IActivationFactory = DynWinRtType.registerInterface('IActivationFactory', WinGuid.parse('00000035-0000-0000-c000-000000000046'))\n    .addMethod('ActivateInstance', new DynWinRtMethodSig().addOut(DynWinRtType.object()));\n");
    }

    // Collect delegate names
    let mut delegate_names: HashSet<String> = delegate_type_names.clone();
    let all_ifaces: Vec<&InterfaceMeta> = class.default_interface.iter()
        .chain(class.factory_interfaces.iter())
        .chain(class.static_interfaces.iter())
        .chain(class.required_interfaces.iter())
        .collect();
    for iface in &all_ifaces {
        for method in &iface.methods {
            for p in &method.params {
                match &p.typ {
                    TypeMeta::Delegate { name, .. } => { delegate_names.insert(name.clone()); }
                    _ => {}
                }
                if method.is_event_add || method.is_event_remove || method.name.starts_with("put_") {
                    if let TypeMeta::Parameterized { name, args, .. } = &p.typ {
                        delegate_names.insert(crate::meta::make_parameterized_name(name, args));
                    }
                }
            }
        }
    }

    // Collection generics import (direct import — no _m_ needed)
    let collection_names = collect_used_generics_from_class(class);
    for cname in &collection_names {
        if !delegate_names.contains(cname) {
            out.push_str(&format!("import {{ {} }} from './{}.mjs';\n", cname, cname));
        }
    }

    // Import delegate IID + PARAM_TYPES
    let mut sorted_delegates: Vec<_> = delegate_names.iter().collect();
    sorted_delegates.sort();
    for dname in &sorted_delegates {
        out.push_str(&format!(
            "import {{ IID_{dname}, {dname}_PARAM_TYPES }} from './{dname}.mjs';\n",
        ));
    }

    // Type imports
    let mut imported_names: HashSet<String> = HashSet::new();
    let imports = collect_type_imports(class);
    let mut sorted_imports: Vec<_> = imports.iter().collect();
    sorted_imports.sort();
    for (_ns, name, kind) in &sorted_imports {
        if known_types.contains(name) && !delegate_names.contains(name) {
            out.push_str(&format_esm_import(name, kind));
            imported_names.insert(name.clone());
            if kind == "interface" {
                imported_names.insert(format!("IID_{}", name));
            }
        }
    }

    // Import shared required interfaces
    for req_iface in &class.required_interfaces {
        if !req_iface.iid.is_empty() && shared_iids.contains(&req_iface.iid) && !imported_names.contains(&req_iface.name) {
            out.push_str(&format_esm_import(&req_iface.name, "interface"));
            imported_names.insert(format!("IID_{}", req_iface.name));
            imported_names.insert(req_iface.name.clone());
        }
    }
    out.push('\n');

    // IID constants for interfaces not already imported
    let all_class_ifaces: Vec<&InterfaceMeta> = class.default_interface.iter()
        .chain(class.factory_interfaces.iter())
        .chain(class.static_interfaces.iter())
        .chain(class.required_interfaces.iter())
        .collect();
    for iface in &all_class_ifaces {
        let iid_name = format!("IID_{}", iface.name);
        if !iface.iid.is_empty() && !imported_names.contains(&iid_name) {
            out.push_str(&format!(
                "const {} = WinGuid.parse('{}');\n",
                iid_name, iface.iid
            ));
        }
    }
    out.push('\n');

    // Interface registrations
    if let Some(ref iface) = class.default_interface {
        let mut reg = generate_interface_registration(iface);
        reg = reg.replacen(&format!("const {} =", iface.name), &format!("const _{} =", iface.name), 1);
        out.push_str(&reg);
        out.push('\n');
    }
    for iface in &class.factory_interfaces {
        let mut reg = generate_interface_registration(iface);
        reg = reg.replacen(&format!("const {} =", iface.name), &format!("const _{} =", iface.name), 1);
        out.push_str(&reg);
        out.push('\n');
    }
    for iface in &class.static_interfaces {
        let mut reg = generate_interface_registration(iface);
        reg = reg.replacen(&format!("const {} =", iface.name), &format!("const _{} =", iface.name), 1);
        out.push_str(&reg);
        out.push('\n');
    }
    for iface in &class.required_interfaces {
        if !iface.iid.is_empty() && shared_iids.contains(&iface.iid) && imported_names.contains(&iface.name) {
            continue;
        }
        let mut reg = generate_interface_registration(iface);
        reg = reg.replacen(&format!("const {} =", iface.name), &format!("const _{} =", iface.name), 1);
        out.push_str(&reg);
        out.push('\n');
    }

    // Struct helpers
    for s in &used_structs {
        out.push_str(&generate_esm_struct_helpers(s));
        out.push('\n');
    }

    // Class declaration
    out.push_str(&format!("export class {} {{\n", class.name));

    // Lazy-cached factory/static interface accessors
    let mut declared: HashSet<String> = HashSet::new();
    for iface in &class.factory_interfaces {
        let key = format!("f_{}", iface.name);
        if !iface.iid.is_empty() && declared.insert(key.clone()) {
            out.push_str(&format!("    static _{k};\n", k = key));
            out.push_str(&format!(
                "    static {k}() {{ return {cls}._{k} ??= DynWinRtValue.activationFactory('{full}').cast(IID_{iface}); }}\n",
                k = key, cls = class.name, iface = iface.name, full = class.full_name
            ));
        }
    }
    for iface in &class.static_interfaces {
        let key = format!("s_{}", iface.name);
        if !iface.iid.is_empty() && declared.insert(key.clone()) {
            out.push_str(&format!("    static _{k};\n", k = key));
            out.push_str(&format!(
                "    static {k}() {{ return {cls}._{k} ??= DynWinRtValue.activationFactory('{full}').cast(IID_{iface}); }}\n",
                k = key, cls = class.name, iface = iface.name, full = class.full_name
            ));
        }
    }

    out.push('\n');
    out.push_str("    constructor(obj) {\n");
    if let Some(ref iface) = class.default_interface {
        if !iface.iid.is_empty() {
            out.push_str(&format!("        this._obj = obj.cast(IID_{});\n", iface.name));
        } else {
            out.push_str("        this._obj = obj;\n");
        }
    } else {
        out.push_str("        this._obj = obj;\n");
    }
    out.push_str("    }\n");

    // Default constructor
    if class.has_default_constructor {
        let has_create_factory = class.factory_interfaces.iter()
            .any(|iface| iface.methods.iter().any(|m| {
                let camel = to_camel_case(&m.name);
                camel == "create" || camel.starts_with("create")
            }));
        let ctor_name = if has_create_factory { "createDefault" } else { "create" };
        out.push('\n');
        out.push_str(&format!(
            "    static {}() {{\n",
            ctor_name
        ));
        out.push_str(&format!(
            "        return new {}(_IActivationFactory.method(6).invoke(DynWinRtValue.activationFactory('{}'), []));\n",
            class.name, class.full_name
        ));
        out.push_str("    }\n");
    }

    // Factory methods
    for iface in &class.factory_interfaces {
        for method in &iface.methods {
            out.push('\n');
            out.push_str(&generate_factory_method(class, iface, method));
        }
    }

    // Static methods
    for iface in &class.static_interfaces {
        for method in &iface.methods {
            out.push('\n');
            out.push_str(&generate_static_method(class, iface, method, known_types));
        }
    }

    // Instance methods (default interface)
    if let Some(ref default_iface) = class.default_interface {
        let iface_var = format!("_{}", default_iface.name);
        for method in &default_iface.methods {
            out.push('\n');
            out.push_str(&generate_instance_method(default_iface, &iface_var, method, known_types, delegate_type_names));
        }
    }

    // Auto-generate close() if class implements IClosable
    const ICLOSABLE_IID: &str = "30d5a829-7fa4-4026-83bb-d75bae4ea99e";
    if class.required_interfaces.iter().any(|ri| ri.iid == ICLOSABLE_IID) {
        out.push('\n');
        out.push_str("    close() {\n");
        out.push_str("        IClosable.from(this._obj).close();\n");
        out.push_str("    }\n");
    }

    // .as() method
    if !class.required_interfaces.is_empty() {
        out.push('\n');
        out.push_str("    as(InterfaceClass) {\n");
        out.push_str("        return InterfaceClass.from(this._obj);\n");
        out.push_str("    }\n");
    }

    out.push_str("}\n");

    // Required interface wrapper classes
    for req_iface in &class.required_interfaces {
        if req_iface.iid.is_empty() { continue; }
        if imported_names.contains(&req_iface.name) {
            continue;
        }
        let reg_var = format!("_{}", req_iface.name);
        out.push('\n');
        out.push_str(&format!("export class {} {{\n", req_iface.name));
        out.push_str("    constructor(obj) {\n");
        out.push_str("        this._obj = obj;\n");
        out.push_str("    }\n\n");
        out.push_str("    static from(obj) {\n");
        out.push_str(&format!(
            "        return new {}(obj.cast(IID_{}));\n",
            req_iface.name, req_iface.name
        ));
        out.push_str("    }\n");
        for method in &req_iface.methods {
            out.push('\n');
            out.push_str(&generate_instance_method(req_iface, &reg_var, method, known_types, delegate_type_names));
        }
        out.push_str("}\n");
    }

    out
}

// ======================================================================
// Private: generate_delegate (ESM version)
// ======================================================================

fn generate_delegate(iface: &InterfaceMeta) -> String {
    let mut out = String::new();

    out.push_str("// Generated by winrt-meta — do not edit (delegate)\n");
    out.push_str("import { createRequire } from 'node:module';\nconst require = createRequire(import.meta.url);\nconst { DynWinRtType, WinGuid } = require('dynwinrt-js');\n\n");

    let invoke = iface.methods.iter().find(|m| m.name == "Invoke");
    let param_exprs: Vec<String> = invoke.map(|inv| {
        inv.params.iter()
            .filter(|p| p.direction == ParamDirection::In)
            .map(|p| ts_dynwinrt_type(&p.typ))
            .collect()
    }).unwrap_or_default();

    if !iface.iid.is_empty() {
        out.push_str(&format!(
            "export const IID_{} = DynWinRtType.parameterized(WinGuid.parse('{}'), [{}]).iid();\n",
            iface.name, iface.iid, param_exprs.join(", ")
        ));
    } else {
        out.push_str(&format!(
            "export const IID_{} = undefined;\n",
            iface.name
        ));
    }

    let invoke = iface.methods.iter().find(|m| m.name == "Invoke");
    if let Some(invoke) = invoke {
        let param_exprs: Vec<String> = invoke.params.iter()
            .filter(|p| p.direction == ParamDirection::In)
            .map(|p| ts_dynwinrt_type(&p.typ))
            .collect();
        out.push_str(&format!(
            "export const {}_PARAM_TYPES = [{}];\n",
            iface.name,
            param_exprs.join(", ")
        ));
    }

    out
}

// ======================================================================
// Private: struct helpers (ESM version — exported, no type annotations)
// ======================================================================

fn generate_esm_struct_helpers(s: &TypeMeta) -> String {
    let (namespace, name, fields) = match s {
        TypeMeta::Struct { namespace, name, fields } => (namespace, name, fields),
        _ => return String::new(),
    };
    let mut out = String::new();

    // unpack function (exported)
    out.push_str(&format!("export function unpack{}(v) {{\n", name));
    out.push_str("    const s = v.asStruct();\n");
    out.push_str("    return { ");
    let field_exprs: Vec<String> = fields.iter().enumerate().map(|(i, f)| {
        format!("{}: {}", to_camel_case(&f.name), struct_field_getter(&f.typ, i))
    }).collect();
    out.push_str(&field_exprs.join(", "));
    out.push_str(" };\n");
    out.push_str("}\n");
    out.push_str(&format!("const _unpack{0} = unpack{0};\n", name));

    // Type constant (exported)
    let full_name = format!("{}.{}", namespace, name);
    let field_types: Vec<String> = fields.iter().map(|f| ts_dynwinrt_type(&f.typ)).collect();
    out.push_str(&format!("export const {}_Type = DynWinRtType.structType('{}', [{}]);\n",
        name, full_name, field_types.join(", ")));
    out.push_str(&format!("const _{0}_Type = {0}_Type;\n", name));

    // pack function (exported)
    out.push_str(&format!("export function pack{}(v) {{\n", name));
    out.push_str(&format!("    const s = DynWinRtStruct.create({}_Type);\n", name));
    for (i, f) in fields.iter().enumerate() {
        out.push_str(&format!("    {};\n", struct_field_setter(&f.typ, i, &format!("v.{}", to_camel_case(&f.name)))));
    }
    out.push_str("    return s;\n");
    out.push_str("}\n");
    out.push_str(&format!("const _pack{0} = pack{0};\n", name));

    out
}

// ======================================================================
// Private: factory method invoke
// ======================================================================

fn generate_factory_method(
    class: &ClassMeta,
    iface: &InterfaceMeta,
    method: &MethodMeta,
) -> String {
    let in_params = get_in_params(method);
    let js_params = js_param_list(&in_params);
    let is_async = method.return_type.as_ref().is_some_and(|rt| rt.is_async());

    let mut out = String::new();
    let async_kw = if is_async { "async " } else { "" };
    out.push_str(&format!(
        "    static {}{}({}) {{\n",
        async_kw, to_camel_case(&method.name), js_params
    ));

    let args_expr = js_build_args_expr(&in_params);
    let invoke_expr = format!(
        "_{iface}.method({idx}).invoke({cls}.f_{iface}(), [{args}])",
        iface = iface.name, idx = method.vtable_index, cls = class.name, args = args_expr
    );

    if is_async {
        out.push_str(&format!(
            "        return new {}(await {}.toPromise());\n",
            class.name, invoke_expr
        ));
    } else {
        out.push_str(&format!(
            "        return new {}({});\n",
            class.name, invoke_expr
        ));
    }
    out.push_str("    }\n");
    out
}

// ======================================================================
// Private: static method invoke
// ======================================================================

fn generate_static_method(
    class: &ClassMeta,
    iface: &InterfaceMeta,
    method: &MethodMeta,
    known_types: &HashSet<String>,
) -> String {
    let in_params = get_in_params(method);
    let js_params = js_param_list(&in_params);

    let return_type = method.return_type.as_ref();
    let is_with_progress = return_type.is_some_and(|rt| matches!(rt,
        TypeMeta::AsyncOperationWithProgress(_, _) | TypeMeta::AsyncActionWithProgress(_)));
    let is_async = return_type.is_some_and(|rt| rt.is_async()) && !is_with_progress;

    let mut out = String::new();
    let statics_call = format!("{cls}.s_{iface}()", cls = class.name, iface = iface.name);

    if method.is_property_getter && in_params.is_empty() {
        let prop_name = to_camel_case(method.name.strip_prefix("get_").unwrap_or(&method.name));
        out.push_str(&format!("    static get {}() {{\n", prop_name));
        let invoke_expr = format!(
            "_{}.method({}).invoke({}, [])",
            iface.name, method.vtable_index, statics_call
        );
        let converted = convert_return(&invoke_expr, return_type, false, known_types, &NO_DEFERRED);
        out.push_str(&format!("        return {};\n", converted));
        out.push_str("    }\n");
    } else {
        let async_kw = if is_async { "async " } else { "" };
        out.push_str(&format!(
            "    static {}{}({}) {{\n",
            async_kw, to_camel_case(&method.name), js_params
        ));
        let args_expr = js_build_args_expr(&in_params);
        let invoke_expr = format!(
            "_{}.method({}).invoke({}, [{}])",
            iface.name, method.vtable_index, statics_call, args_expr
        );
        if is_with_progress {
            let inner_type = match return_type {
                Some(TypeMeta::AsyncOperationWithProgress(inner, _)) => Some(inner.as_ref()),
                _ => None,
            };
            let inner_convert = convert_return("await _op.toPromise()", inner_type, false, known_types, &NO_DEFERRED);
            out.push_str(&format!("        const _op = {};\n", invoke_expr));
            out.push_str(         "        const _w = {\n");
            out.push_str(         "            progress(cb) { _op.onProgress(cb); return _w; },\n");
            out.push_str(&format!("            async toPromise() {{ return {}; }},\n", inner_convert));
            out.push_str(         "            then(res, rej) { return _w.toPromise().then(res, rej); },\n");
            out.push_str(         "        };\n");
            out.push_str(         "        return _w;\n");
        } else {
            let converted = convert_return(&invoke_expr, return_type, is_async, known_types, &NO_DEFERRED);
            out.push_str(&format!("        return {};\n", converted));
        }
        out.push_str("    }\n");
    }
    out
}

// ======================================================================
// Private: instance method
// ======================================================================

fn generate_instance_method(
    _iface: &InterfaceMeta,
    iface_var: &str,
    method: &MethodMeta,
    known_types: &HashSet<String>,
    delegate_type_names: &HashSet<String>,
) -> String {
    generate_method_body(iface_var, "this._obj", method, known_types, delegate_type_names, None)
}

fn generate_method_body(
    iface_var: &str,
    obj_expr: &str,
    method: &MethodMeta,
    known_types: &HashSet<String>,
    delegate_type_names: &HashSet<String>,
    js_name_override: Option<&str>,
) -> String {
    let in_params = get_in_params(method);
    let return_type = method.return_type.as_ref();
    let is_with_progress = return_type.is_some_and(|rt| matches!(rt,
        TypeMeta::AsyncOperationWithProgress(_, _) | TypeMeta::AsyncActionWithProgress(_)));
    let is_async = return_type.is_some_and(|rt| rt.is_async()) && !is_with_progress;
    let has_array_out = method.params.iter().any(|p| {
        (p.direction == ParamDirection::Out || p.direction == ParamDirection::OutFill)
            && matches!(p.typ, TypeMeta::Array(_))
    });
    let has_return = return_type.is_some() || has_array_out;

    let mut out = String::new();

    // Event add
    if method.is_event_add {
        let event_name = to_camel_case(method.name.strip_prefix("add_").unwrap_or(&method.name));
        let delegate_name = in_params.first().and_then(|p| match &p.typ {
            TypeMeta::Parameterized { name, args, .. } =>
                Some(crate::meta::make_parameterized_name(name, args)),
            TypeMeta::Delegate { name, .. } => Some(name.clone()),
            _ => None,
        });
        out.push_str(&format!(
            "    on{}(callback) {{\n",
            capitalize(&event_name)
        ));
        if let Some(ref dname) = delegate_name {
            out.push_str(&format!(
                "        const handler = DynWinRtDelegate.create(IID_{}, {}_PARAM_TYPES, callback);\n",
                dname, dname
            ));
        } else {
            out.push_str(
                "        const handler = DynWinRtDelegate.create(DynWinRtType.object().iid(), [DynWinRtType.object(), DynWinRtType.object()], callback);\n"
            );
        }
        out.push_str(&format!(
            "        return {}.method({}).invoke({}, [handler.toValue()]);\n",
            iface_var, method.vtable_index, obj_expr
        ));
        out.push_str("    }\n");
        return out;
    }
    // Event remove
    if method.is_event_remove {
        let event_name = to_camel_case(method.name.strip_prefix("remove_").unwrap_or(&method.name));
        out.push_str(&format!(
            "    off{}(token) {{\n",
            capitalize(&event_name)
        ));
        out.push_str(&format!(
            "        {}.method({}).invoke({}, [token]);\n",
            iface_var, method.vtable_index, obj_expr
        ));
        out.push_str("    }\n");
        return out;
    }

    let is_delegate_type = |typ: Option<&TypeMeta>| -> bool {
        match typ {
            Some(TypeMeta::Delegate { .. }) => true,
            Some(TypeMeta::Interface { name, .. }) => delegate_type_names.contains(name),
            _ => false,
        }
    };

    if method.is_property_getter && in_params.is_empty() {
        let prop_name = to_camel_case(method.name.strip_prefix("get_").unwrap_or(&method.name));
        out.push_str(&format!("    get {}() {{\n", prop_name));
        let invoke_expr = format!(
            "{}.method({}).invoke({}, [])",
            iface_var, method.vtable_index, obj_expr
        );
        let converted = if is_delegate_type(return_type) {
            invoke_expr.clone()
        } else {
            convert_return(&invoke_expr, return_type, false, known_types, &NO_DEFERRED)
        };
        out.push_str(&format!("        return {};\n", converted));
        out.push_str("    }\n");
    } else if method.is_property_setter {
        let prop_name = to_camel_case(method.name.strip_prefix("put_").unwrap_or(&method.name));
        out.push_str(&format!("    set {}(value) {{\n", prop_name));
        let arg = in_params.first()
            .map(|p| js_wrap_arg("value", &p.typ))
            .unwrap_or_else(|| "value".to_string());
        out.push_str(&format!(
            "        {}.method({}).invoke({}, [{}]);\n",
            iface_var, method.vtable_index, obj_expr, arg
        ));
        out.push_str("    }\n");
    } else {
        let js_params = js_param_list(&in_params);
        let array_out_elem = if has_array_out && return_type.is_none() {
            method.params.iter().find_map(|p| {
                if p.direction == ParamDirection::Out || p.direction == ParamDirection::OutFill {
                    if let TypeMeta::Array(inner) = &p.typ { Some(inner.as_ref()) } else { None }
                } else { None }
            })
        } else { None };
        let method_name = js_name_override.map(|s| s.to_string()).unwrap_or_else(|| to_camel_case(&method.name));
        let async_kw = if is_async { "async " } else { "" };

        out.push_str(&format!(
            "    {}{}({}) {{\n",
            async_kw, method_name, js_params
        ));

        let args_expr = js_build_args_expr(&in_params);
        let invoke_expr = format!(
            "{}.method({}).invoke({}, [{}])",
            iface_var, method.vtable_index, obj_expr, args_expr
        );

        if is_with_progress {
            let inner_type = match return_type {
                Some(TypeMeta::AsyncOperationWithProgress(inner, _)) => Some(inner.as_ref()),
                _ => None,
            };
            let inner_convert = convert_return("await _op.toPromise()", inner_type, false, known_types, &NO_DEFERRED);
            out.push_str(&format!("        const _op = {};\n", invoke_expr));
            out.push_str(         "        const _w = {\n");
            out.push_str(         "            progress(cb) { _op.onProgress(cb); return _w; },\n");
            out.push_str(&format!("            async toPromise() {{ return {}; }},\n", inner_convert));
            out.push_str(         "            then(res, rej) { return _w.toPromise().then(res, rej); },\n");
            out.push_str(         "        };\n");
            out.push_str(         "        return _w;\n");
        } else if !has_return && !is_async {
            out.push_str(&format!("        {};\n", invoke_expr));
        } else if let Some(elem) = array_out_elem {
            let arr_expr = format!("{}.asArray()", invoke_expr);
            let converted = convert_array_return(&arr_expr, elem, known_types, &NO_DEFERRED);
            out.push_str(&format!("        return {};\n", converted));
        } else {
            let converted = convert_return(&invoke_expr, return_type, is_async, known_types, &NO_DEFERRED);
            out.push_str(&format!("        return {};\n", converted));
        }
        out.push_str("    }\n");
    }

    out
}
