use std::collections::HashSet;

use crate::meta::{ClassMeta, InterfaceMeta, MethodMeta, ParamDirection};
use crate::types::TypeMeta;

use super::common::{
    NO_DEFERRED, collect_used_structs_from_class, collect_used_structs_from_iface,
    ts_struct_field_type, struct_field_getter, struct_field_setter,
    build_method_sig, ts_dynwinrt_type, build_args_expr, wrap_arg,
    convert_array_return, convert_return,
    generate_interface_registration, trim_trailing_newline_add_semicolon,
    collect_used_generics_from_methods, collect_used_generics_from_class,
    collect_iface_type_imports, collect_type_imports,
    get_in_params, to_camel_case, capitalize,
};

/// Generate an index.ts that re-exports all generated types.
pub fn generate_index(classes: &[ClassMeta], interfaces: &[InterfaceMeta], enums: &[TypeMeta]) -> String {
    let mut out = String::new();
    let mut seen: HashSet<String> = HashSet::new();
    out.push_str("// Generated by winrt-meta — do not edit\n");
    let mut sorted_classes: Vec<_> = classes.iter().collect();
    sorted_classes.sort_by(|a, b| a.name.cmp(&b.name));
    for class in sorted_classes {
        if seen.insert(class.name.clone()) {
            let struct_names: Vec<_> = collect_used_structs_from_class(class).iter()
                .flat_map(|s| ts_struct_export_names(s))
                .filter(|n| seen.insert(n.clone()))
                .collect();
            if struct_names.is_empty() {
                out.push_str(&format!("export {{ {} }} from './{}';\n", class.name, class.name));
            } else {
                out.push_str(&format!("export {{ {}, {} }} from './{}';\n", class.name, struct_names.join(", "), class.name));
            }
        }
    }
    let mut sorted_ifaces: Vec<_> = interfaces.iter().collect();
    sorted_ifaces.sort_by(|a, b| a.name.cmp(&b.name));
    for iface in sorted_ifaces {
        if !seen.insert(iface.name.clone()) {
            continue;
        }
        let is_delegate = iface.methods.iter().any(|m| m.name == ".ctor")
            && iface.methods.iter().any(|m| m.name == "Invoke");
        let struct_names: Vec<_> = collect_used_structs_from_iface(iface).iter()
            .flat_map(|s| ts_struct_export_names(s))
            .filter(|n| seen.insert(n.clone()))
            .collect();
        if is_delegate {
            out.push_str(&format!(
                "export {{ IID_{iname}, {iname}_PARAM_TYPES }} from './{iname}.js';\n",
                iname = iface.name
            ));
        } else {
            if struct_names.is_empty() {
                out.push_str(&format!(
                    "export {{ IID_{iname}, {iname} }} from './{iname}.js';\n",
                    iname = iface.name
                ));
            } else {
                out.push_str(&format!(
                    "export {{ IID_{iname}, {iname}, {structs} }} from './{iname}.js';\n",
                    iname = iface.name, structs = struct_names.join(", ")
                ));
            }
        }
    }
    let mut sorted_enums: Vec<_> = enums.iter().collect();
    sorted_enums.sort_by(|a, b| {
        let name_a = match a { TypeMeta::Enum { name, .. } => name.as_str(), _ => "" };
        let name_b = match b { TypeMeta::Enum { name, .. } => name.as_str(), _ => "" };
        name_a.cmp(name_b)
    });
    for en in sorted_enums {
        if let TypeMeta::Enum { name, .. } = en {
            if seen.insert(name.clone()) {
                out.push_str(&format!("export {{ {} }} from './{}';\n", name, name));
            }
        }
    }
    out
}

// ======================================================================
// Public: append_to_index — merge new types into an existing ESM index
// ======================================================================

pub fn append_to_index(
    existing: &str,
    classes: &[ClassMeta],
    interfaces: &[InterfaceMeta],
    enums: &[TypeMeta],
) -> String {
    // Parse existing export lines to find already-exported names and modules
    let mut seen: HashSet<String> = HashSet::new();
    let mut exported_modules: HashSet<String> = HashSet::new();
    for line in existing.lines() {
        // Match: export { Foo } from './Foo';
        // Match: export { IID_IBar, IBar } from './IBar';
        if line.starts_with("export {") {
            if let Some(start) = line.find('{') {
                if let Some(end) = line.find('}') {
                    for name in line[start + 1..end].split(',') {
                        let name = name.trim();
                        if !name.is_empty() {
                            seen.insert(name.to_string());
                        }
                    }
                }
            }
            // Track module name from `from './Foo.js'`
            if let Some(start) = line.find("from './") {
                if let Some(end) = line[start + 8..].find("'") {
                    let module = &line[start + 8..start + 8 + end];
                    let module = module.strip_suffix(".js").unwrap_or(module);
                    exported_modules.insert(module.to_string());
                }
            }
        }
    }

    let mut out = existing.to_string();
    if !out.ends_with('\n') {
        out.push('\n');
    }

    // Add new classes
    let mut sorted_classes: Vec<_> = classes.iter().collect();
    sorted_classes.sort_by(|a, b| a.name.cmp(&b.name));
    for class in sorted_classes {
        if !exported_modules.contains(&class.name) && seen.insert(class.name.clone()) {
            let struct_names: Vec<_> = collect_used_structs_from_class(class).iter()
                .flat_map(|s| ts_struct_export_names(s))
                .filter(|n| seen.insert(n.clone()))
                .collect();
            if struct_names.is_empty() {
                out.push_str(&format!("export {{ {} }} from './{}';\n", class.name, class.name));
            } else {
                out.push_str(&format!("export {{ {}, {} }} from './{}';\n", class.name, struct_names.join(", "), class.name));
            }
        }
    }

    // Add new interfaces
    let mut sorted_ifaces: Vec<_> = interfaces.iter().collect();
    sorted_ifaces.sort_by(|a, b| a.name.cmp(&b.name));
    for iface in sorted_ifaces {
        if exported_modules.contains(&iface.name) || !seen.insert(iface.name.clone()) { continue; }
        let is_delegate = iface.methods.iter().any(|m| m.name == ".ctor")
            && iface.methods.iter().any(|m| m.name == "Invoke");
        let struct_names: Vec<_> = collect_used_structs_from_iface(iface).iter()
            .flat_map(|s| ts_struct_export_names(s))
            .filter(|n| seen.insert(n.clone()))
            .collect();
        if is_delegate {
            out.push_str(&format!(
                "export {{ IID_{0}, {0}_PARAM_TYPES }} from './{0}.js';\n",
                iface.name
            ));
        } else {
            if struct_names.is_empty() {
                out.push_str(&format!(
                    "export {{ IID_{0}, {0} }} from './{0}.js';\n",
                    iface.name
                ));
            } else {
                out.push_str(&format!(
                    "export {{ IID_{0}, {0}, {1} }} from './{0}.js';\n",
                    iface.name, struct_names.join(", ")
                ));
            }
        }
    }

    // Add new enums
    let mut sorted_enums: Vec<_> = enums.iter().collect();
    sorted_enums.sort_by(|a, b| {
        let name_a = match a { TypeMeta::Enum { name, .. } => name.as_str(), _ => "" };
        let name_b = match b { TypeMeta::Enum { name, .. } => name.as_str(), _ => "" };
        name_a.cmp(name_b)
    });
    for en in sorted_enums {
        if let TypeMeta::Enum { name, .. } = en {
            if !exported_modules.contains(name) && seen.insert(name.clone()) {
                out.push_str(&format!("export {{ {} }} from './{}';\n", name, name));
            }
        }
    }

    out
}

/// Generate a TypeScript file for a single enum.
pub fn generate_enum(en: &TypeMeta) -> Option<String> {
    let (name, members) = match en {
        TypeMeta::Enum { name, members, .. } => (name, members),
        _ => return None,
    };

    let mut out = String::new();
    out.push_str("// Generated by winrt-meta — do not edit\n\n");
    out.push_str(&format!("export enum {} {{\n", name));
    for member in members {
        out.push_str(&format!("    {} = {},\n", member.name, member.value));
    }
    out.push_str("}\n");
    Some(out)
}

/// Generate a TypeScript file for a WinRT interface (non-exclusive).
/// Outputs IID, registerInterface, and a wrapper class with typed methods.
pub fn generate_interface(iface: &InterfaceMeta, known_types: &HashSet<String>, delegate_type_names: &HashSet<String>) -> String {
    // Detect delegate types (have .ctor + Invoke methods)
    let is_delegate = iface.methods.iter().any(|m| m.name == ".ctor")
        && iface.methods.iter().any(|m| m.name == "Invoke");
    if is_delegate {
        return generate_delegate(iface);
    }

    // Collect structs used in interface methods
    let used_structs = collect_used_structs_from_iface(iface);
    let has_structs = !used_structs.is_empty();

    let mut out = String::new();
    out.push_str("// Generated by winrt-meta — do not edit\n");
    if has_structs {
        out.push_str("import { DynWinRtType, DynWinRtMethodSig, DynWinRtValue, DynWinRtArray, DynWinRtStruct, DynWinRtDelegate, WinGuid } from 'dynwinrt-js';\n");
    } else {
        out.push_str("import { DynWinRtType, DynWinRtMethodSig, DynWinRtValue, DynWinRtArray, DynWinRtDelegate, WinGuid } from 'dynwinrt-js';\n");
    }
    // Collect delegate names — delegates don't export classes, only IID + PARAM_TYPES
    let mut delegate_names: HashSet<String> = delegate_type_names.clone();
    for method in &iface.methods {
        for p in &method.params {
            match &p.typ {
                TypeMeta::Delegate { name, .. } => { delegate_names.insert(name.clone()); }
                _ => {}
            }
            // Parameterized delegates used in event add/remove methods
            if method.is_event_add || method.is_event_remove {
                if let TypeMeta::Parameterized { name, args, .. } = &p.typ {
                    delegate_names.insert(crate::meta::make_parameterized_name(name, args));
                }
            }
        }
    }

    // Import parameterized collection types (skip delegates — they don't export classes)
    let collection_names = collect_used_generics_from_methods(&iface.methods);
    for cname in &collection_names {
        if cname != &iface.name && !delegate_names.contains(cname) {
            out.push_str(&format!("import {{ {} }} from './{}';\n", cname, cname));
        }
    }

    // Import delegate IID + PARAM_TYPES for event methods
    let mut sorted_delegates: Vec<_> = delegate_names.iter().collect();
    sorted_delegates.sort();
    for dname in &sorted_delegates {
        out.push_str(&format!(
            "import {{ IID_{dname}, {dname}_PARAM_TYPES }} from './{dname}.js';\n",
        ));
    }

    // Type imports for referenced types (enums, classes, other interfaces)
    // Skip delegate names — they don't export classes, only IID + PARAM_TYPES
    let type_imports = collect_iface_type_imports(iface);
    let mut sorted_type_imports: Vec<_> = type_imports.iter().collect();
    sorted_type_imports.sort();
    for (_ns, name, kind) in &sorted_type_imports {
        if known_types.contains(name) && !delegate_names.contains(name) {
            out.push_str(&format_type_import(name, kind));
        }
    }
    out.push('\n');

    // IID constant — for parameterized interfaces, compute from PIID + type args
    if let Some(ref piid) = iface.generic_piid {
        let args_ts: Vec<String> = iface.generic_args.iter().map(|a| ts_dynwinrt_type(a)).collect();
        out.push_str(&format!(
            "export const IID_{} = DynWinRtType.parameterized(WinGuid.parse('{}'), [{}]).iid()!;\n\n",
            iface.name, piid, args_ts.join(", ")
        ));
    } else if !iface.iid.is_empty() {
        out.push_str(&format!(
            "export const IID_{} = WinGuid.parse('{}');\n\n",
            iface.name, iface.iid
        ));
    }

    // Interface registration (private const, used by wrapper class)
    out.push_str(&format!("const _{} = DynWinRtType.registerInterface(\n", iface.name));
    out.push_str(&format!("    \"{}\", IID_{})\n", iface.name, iface.name));

    for method in &iface.methods {
        out.push_str(&format!(
            "    .addMethod(\"{}\", {})\n",
            method.name,
            build_method_sig(method)
        ));
    }
    trim_trailing_newline_add_semicolon(&mut out);
    out.push('\n');

    // Struct interface + unpack/pack helpers
    for s in &used_structs {
        out.push_str(&generate_struct_helpers(s));
        out.push('\n');
    }

    // Wrapper class
    out.push_str(&format!("export class {} {{\n", iface.name));
    out.push_str("    readonly _obj: DynWinRtValue;\n\n");
    if iface.generic_piid.is_some() {
        // Parameterized interfaces need QI cast in constructor
        out.push_str("    constructor(obj: DynWinRtValue) {\n");
        out.push_str(&format!("        this._obj = obj.cast(IID_{});\n", iface.name));
        out.push_str("    }\n");
    } else {
        out.push_str("    constructor(obj: DynWinRtValue) {\n");
        out.push_str("        this._obj = obj;\n");
        out.push_str("    }\n");
    }

    // static from() — QI cast
    if !iface.iid.is_empty() {
        out.push('\n');
        out.push_str(&format!(
            "    static from(obj: DynWinRtValue): {} {{\n",
            iface.name
        ));
        out.push_str(&format!(
            "        return new {}(obj.cast(IID_{}));\n",
            iface.name, iface.name
        ));
        out.push_str("    }\n");
    }

    // static create() for IVector<T> and IMap<K,V>
    if let Some(ref piid) = iface.generic_piid {
        if piid == "913337e9-11a1-4345-a3a2-4e7f956e222d" && iface.generic_args.len() == 1 {
            // IVector<T>
            let elem_type = ts_dynwinrt_type(&iface.generic_args[0]);
            out.push('\n');
            out.push_str(&format!(
                "    /** Create a new IVector from an array of items. */\n\
                 \x20   static create(items: DynWinRtValue[]): {} {{\n\
                 \x20       return new {}(DynWinRtValue.createVector(items.map(i => (i as any)._obj || i), {}));\n\
                 \x20   }}\n",
                iface.name, iface.name, elem_type
            ));
        } else if piid == "3c2925fe-8519-45c1-aa79-197b6718c1c1" && iface.generic_args.len() == 2 {
            // IMap<K,V>
            let key_type = ts_dynwinrt_type(&iface.generic_args[0]);
            let val_type = ts_dynwinrt_type(&iface.generic_args[1]);
            out.push('\n');
            out.push_str(&format!(
                "    /** Create a new IMap from parallel arrays of keys and values. */\n\
                 \x20   static create(keys: DynWinRtValue[], values: DynWinRtValue[]): {} {{\n\
                 \x20       return new {}(DynWinRtValue.createMap(keys.map(k => (k as any)._obj || k), values.map(v => (v as any)._obj || v), {}, {}));\n\
                 \x20   }}\n",
                iface.name, iface.name, key_type, val_type
            ));
        }
    }

    // Instance methods
    let iface_var = format!("_{}", iface.name);
    for method in &iface.methods {
        out.push('\n');
        out.push_str(&generate_iface_instance_method(iface, &iface_var, method, known_types, &delegate_type_names));
    }

    out.push_str("}\n");
    out
}

/// Generate a TypeScript file for a delegate type.
/// Exports the IID constant and Invoke param types for use with DynWinRtDelegate.create().
pub(crate) fn generate_delegate(iface: &InterfaceMeta) -> String {
    let mut out = String::new();
    out.push_str("// Generated by winrt-meta — do not edit (delegate)\n");
    out.push_str("import { DynWinRtType, WinGuid } from 'dynwinrt-js';\n\n");

    // Export IID — compute from piid + Invoke param types at load time
    let invoke = iface.methods.iter().find(|m| m.name == "Invoke");
    let param_exprs: Vec<String> = invoke.map(|inv| {
        inv.params.iter()
            .filter(|p| p.direction == ParamDirection::In)
            .map(|p| ts_dynwinrt_type(&p.typ))
            .collect()
    }).unwrap_or_default();

    if !iface.iid.is_empty() {
        out.push_str(&format!(
            "export const IID_{} = DynWinRtType.parameterized(WinGuid.parse('{}'), [{}]).iid()!;\n",
            iface.name, iface.iid, param_exprs.join(", ")
        ));
    } else {
        out.push_str(&format!(
            "export const IID_{}: any = undefined;\n",
            iface.name
        ));
    }

    // Export Invoke param types as an array for DynWinRtDelegate.create()
    let invoke = iface.methods.iter().find(|m| m.name == "Invoke");
    if let Some(invoke) = invoke {
        let param_exprs: Vec<String> = invoke.params.iter()
            .filter(|p| p.direction == ParamDirection::In)
            .map(|p| ts_dynwinrt_type(&p.typ))
            .collect();
        out.push_str(&format!(
            "export const {}_PARAM_TYPES = [{}];\n",
            iface.name,
            param_exprs.join(", ")
        ));
    }

    out
}

// ======================================================================
// Struct helpers: TS interface + _unpack/_pack functions
// ======================================================================


/// Generate TS interface + _unpack/_pack helpers for a single struct type.
fn generate_struct_helpers(s: &TypeMeta) -> String {
    let (namespace, name, fields) = match s {
        TypeMeta::Struct { namespace, name, fields } => (namespace, name, fields),
        _ => return String::new(),
    };
    let mut out = String::new();

    // TS interface (exported)
    out.push_str(&format!("export interface {} {{\n", name));
    for f in fields {
        out.push_str(&format!("    {}: {};\n", to_camel_case(&f.name), ts_struct_field_type(&f.typ)));
    }
    out.push_str("}\n");

    // unpack function (exported)
    out.push_str(&format!("export function unpack{}(v: DynWinRtValue): {} {{\n", name, name));
    out.push_str("    const s = v.asStruct();\n");
    out.push_str("    return { ");
    let field_exprs: Vec<String> = fields.iter().enumerate().map(|(i, f)| {
        format!("{}: {}", to_camel_case(&f.name), struct_field_getter(&f.typ, i))
    }).collect();
    out.push_str(&field_exprs.join(", "));
    out.push_str(" };\n");
    out.push_str("}\n");
    // Internal alias for generated code
    out.push_str(&format!("const _unpack{0} = unpack{0};\n", name));

    // Type constant (exported)
    let full_name = format!("{}.{}", namespace, name);
    let field_types: Vec<String> = fields.iter().map(|f| ts_dynwinrt_type(&f.typ)).collect();
    out.push_str(&format!("export const {}_Type = DynWinRtType.structType('{}', [{}]);\n",
        name, full_name, field_types.join(", ")));
    // Internal alias for generated code
    out.push_str(&format!("const _{0}_Type = {0}_Type;\n", name));

    // pack function (exported)
    out.push_str(&format!("export function pack{}(v: {}): DynWinRtStruct {{\n", name, name));
    out.push_str(&format!("    const s = DynWinRtStruct.create({}_Type);\n", name));
    for (i, f) in fields.iter().enumerate() {
        out.push_str(&format!("    {};\n", struct_field_setter(&f.typ, i, &format!("v.{}", to_camel_case(&f.name)))));
    }
    out.push_str("    return s;\n");
    out.push_str("}\n");
    // Internal alias for generated code
    out.push_str(&format!("const _pack{0} = pack{0};\n", name));

    out
}

/// Returns the exported names for struct helpers of a given struct type (for TS index).
fn ts_struct_export_names(s: &TypeMeta) -> Vec<String> {
    match s {
        TypeMeta::Struct { name, .. } => vec![
            // Note: name itself is a TS interface (pure type), not exported in JS.
            format!("{}_Type", name),
            format!("pack{}", name),
            format!("unpack{}", name),
        ],
        _ => vec![],
    }
}

/// Generate a TypeScript file for a single RuntimeClass.
/// Uses `registerInterface` + `invoke` pattern.
pub fn generate_class(class: &ClassMeta, known_types: &HashSet<String>, delegate_type_names: &HashSet<String>, shared_iids: &HashSet<String>) -> String {
    // Collect structs used in all method signatures (needed for import and helpers)
    let used_structs = collect_used_structs_from_class(class);
    let has_structs = !used_structs.is_empty();

    let mut out = String::new();

    // Header
    out.push_str("// Generated by winrt-meta — do not edit\n");
    if has_structs {
        out.push_str("import { DynWinRtType, DynWinRtMethodSig, DynWinRtValue, DynWinRtArray, DynWinRtStruct, DynWinRtDelegate, WinGuid } from 'dynwinrt-js';\n");
    } else {
        out.push_str("import { DynWinRtType, DynWinRtMethodSig, DynWinRtValue, DynWinRtArray, DynWinRtDelegate, WinGuid } from 'dynwinrt-js';\n");
    }

    // Collect delegate names from all interfaces of this class
    let mut delegate_names: HashSet<String> = delegate_type_names.clone();
    let all_ifaces: Vec<&InterfaceMeta> = class.default_interface.iter()
        .chain(class.factory_interfaces.iter())
        .chain(class.static_interfaces.iter())
        .chain(class.required_interfaces.iter())
        .collect();
    for iface in &all_ifaces {
        for method in &iface.methods {
            for p in &method.params {
                match &p.typ {
                    TypeMeta::Delegate { name, .. } => { delegate_names.insert(name.clone()); }
                    _ => {}
                }
                if method.is_event_add || method.is_event_remove {
                    if let TypeMeta::Parameterized { name, args, .. } = &p.typ {
                        delegate_names.insert(crate::meta::make_parameterized_name(name, args));
                    }
                }
            }
        }
    }

    // Collection generics import (skip delegates)
    let collection_names = collect_used_generics_from_class(class);
    for cname in &collection_names {
        if !delegate_names.contains(cname) {
            out.push_str(&format!("import {{ {} }} from './{}';\n", cname, cname));
        }
    }

    // Import delegate IID + PARAM_TYPES for event methods
    let mut sorted_delegates: Vec<_> = delegate_names.iter().collect();
    sorted_delegates.sort();
    for dname in &sorted_delegates {
        out.push_str(&format!(
            "import {{ IID_{dname}, {dname}_PARAM_TYPES }} from './{dname}.js';\n",
        ));
    }

    // Type imports — only for types that have generated .ts files (skip delegates)
    // Track imported names to avoid redeclaring them as local constants
    let mut imported_names: HashSet<String> = HashSet::new();
    let imports = collect_type_imports(class);
    let mut sorted_imports: Vec<_> = imports.iter().collect();
    sorted_imports.sort();
    for (_ns, name, kind) in &sorted_imports {
        if known_types.contains(name) && !delegate_names.contains(name) {
            out.push_str(&format_type_import(name, kind));
            imported_names.insert(name.clone());
            if kind == "interface" {
                imported_names.insert(format!("IID_{}", name));
            }
        }
    }

    // Import shared required interfaces from their own files
    for req_iface in &class.required_interfaces {
        if !req_iface.iid.is_empty() && shared_iids.contains(&req_iface.iid) && !imported_names.contains(&req_iface.name) {
            out.push_str(&format_type_import(&req_iface.name, "interface"));
            imported_names.insert(req_iface.name.clone());
            imported_names.insert(format!("IID_{}", req_iface.name));
        }
    }
    out.push('\n');

    // IID constants for all interfaces used by this class (skip if already imported)
    let all_class_ifaces: Vec<&InterfaceMeta> = class.default_interface.iter()
        .chain(class.factory_interfaces.iter())
        .chain(class.static_interfaces.iter())
        .chain(class.required_interfaces.iter())
        .collect();
    for iface in &all_class_ifaces {
        let iid_name = format!("IID_{}", iface.name);
        if !iface.iid.is_empty() && !imported_names.contains(&iid_name) {
            out.push_str(&format!(
                "const {} = WinGuid.parse('{}');\n",
                iid_name, iface.iid
            ));
        }
    }
    out.push('\n');

    // Interface registrations — all use _ prefix to avoid conflicts with imports
    if let Some(ref iface) = class.default_interface {
        let mut reg = generate_interface_registration(iface);
        reg = reg.replacen(&format!("const {} =", iface.name), &format!("const _{} =", iface.name), 1);
        out.push_str(&reg);
        out.push('\n');
    }
    for iface in &class.factory_interfaces {
        let mut reg = generate_interface_registration(iface);
        reg = reg.replacen(&format!("const {} =", iface.name), &format!("const _{} =", iface.name), 1);
        out.push_str(&reg);
        out.push('\n');
    }
    for iface in &class.static_interfaces {
        let mut reg = generate_interface_registration(iface);
        reg = reg.replacen(&format!("const {} =", iface.name), &format!("const _{} =", iface.name), 1);
        out.push_str(&reg);
        out.push('\n');
    }
    for iface in &class.required_interfaces {
        // Skip inline registration for shared interfaces (imported from shared file)
        if !iface.iid.is_empty() && shared_iids.contains(&iface.iid) && imported_names.contains(&iface.name) {
            continue;
        }
        let mut reg = generate_interface_registration(iface);
        reg = reg.replacen(&format!("const {} =", iface.name), &format!("const _{} =", iface.name), 1);
        out.push_str(&reg);
        out.push('\n');
    }

    // IActivationFactory for default constructor (ActivateInstance at vtable index 6)
    if class.has_default_constructor {
        out.push_str("const _IActivationFactory = DynWinRtType.registerInterface('IActivationFactory', WinGuid.parse('00000035-0000-0000-c000-000000000046'))\n    .addMethod('ActivateInstance', new DynWinRtMethodSig().addOut(DynWinRtType.object()));\n");
        out.push('\n');
    }

    // Struct interface + unpack/pack helpers
    for s in &used_structs {
        out.push_str(&generate_struct_helpers(s));
        out.push('\n');
    }

    // Class declaration
    out.push_str(&format!("export class {} {{\n", class.name));
    out.push_str("    readonly _obj: DynWinRtValue;\n");

    // Lazy-cached factory/static interface accessors
    let mut declared: HashSet<String> = HashSet::new();
    for iface in &class.factory_interfaces {
        let key = format!("f_{}", iface.name);
        if !iface.iid.is_empty() && declared.insert(key.clone()) {
            out.push_str(&format!("    private static _{k}: DynWinRtValue;\n", k = key));
            out.push_str(&format!(
                "    private static {k}() {{ return {cls}._{k} ??= DynWinRtValue.activationFactory('{full}').cast(IID_{iface}); }}\n",
                k = key, cls = class.name, iface = iface.name, full = class.full_name
            ));
        }
    }
    for iface in &class.static_interfaces {
        let key = format!("s_{}", iface.name);
        if !iface.iid.is_empty() && declared.insert(key.clone()) {
            out.push_str(&format!("    private static _{k}: DynWinRtValue;\n", k = key));
            out.push_str(&format!(
                "    private static {k}() {{ return {cls}._{k} ??= DynWinRtValue.activationFactory('{full}').cast(IID_{iface}); }}\n",
                k = key, cls = class.name, iface = iface.name, full = class.full_name
            ));
        }
    }

    out.push('\n');
    out.push_str("    constructor(obj: DynWinRtValue) {\n");
    if let Some(ref iface) = class.default_interface {
        if !iface.iid.is_empty() {
            out.push_str(&format!("        this._obj = obj.cast(IID_{});\n", iface.name));
        } else {
            out.push_str("        this._obj = obj;\n");
        }
    } else {
        out.push_str("        this._obj = obj;\n");
    }
    out.push_str("    }\n");

    // Default constructor
    if class.has_default_constructor {
        let has_create_factory = class.factory_interfaces.iter()
            .any(|iface| iface.methods.iter().any(|m| {
                let camel = to_camel_case(&m.name);
                camel == "create" || camel.starts_with("create")
            }));
        let ctor_name = if has_create_factory { "createDefault" } else { "create" };
        out.push('\n');
        out.push_str(&format!(
            "    static {}(): {} {{\n",
            ctor_name, class.name
        ));
        // activationFactory returns IActivationFactory; invoke ActivateInstance (vtable 6) to get instance
        out.push_str(&format!(
            "        return new {}(_IActivationFactory.method(6).invoke(DynWinRtValue.activationFactory('{}'), []));\n",
            class.name, class.full_name
        ));
        out.push_str("    }\n");
    }

    // Factory methods
    for iface in &class.factory_interfaces {
        for method in &iface.methods {
            out.push('\n');
            out.push_str(&generate_factory_method_invoke(class, iface, method, known_types));
        }
    }

    // Static methods
    for iface in &class.static_interfaces {
        for method in &iface.methods {
            out.push('\n');
            out.push_str(&generate_static_method_invoke(class, iface, method, known_types));
        }
    }

    // Instance methods: only default interface methods go directly on the class.
    // Non-default interface methods are accessed via .as(InterfaceWrapper).
    if let Some(ref default_iface) = class.default_interface {
        let iface_var = format!("_{}", default_iface.name);
        for method in &default_iface.methods {
            out.push('\n');
            out.push_str(&generate_iface_instance_method(default_iface, &iface_var, method, known_types, &delegate_type_names));
        }
    }

    // Auto-generate close() if class implements IClosable
    const ICLOSABLE_IID: &str = "30d5a829-7fa4-4026-83bb-d75bae4ea99e";
    if class.required_interfaces.iter().any(|ri| ri.iid == ICLOSABLE_IID) {
        out.push('\n');
        out.push_str("    close(): void {\n");
        out.push_str("        IClosable.from(this._obj).close();\n");
        out.push_str("    }\n");
    }

    // .as() method for accessing non-default interfaces
    // Uses static from() which does QI cast internally
    if !class.required_interfaces.is_empty() {
        out.push('\n');
        out.push_str("    as<T>(InterfaceClass: { from(obj: DynWinRtValue): T }): T {\n");
        out.push_str("        return InterfaceClass.from(this._obj);\n");
        out.push_str("    }\n");
    }

    out.push_str("}\n");

    // Generate inline wrapper classes for required interfaces (non-default)
    // so they can be used with .as()
    // Skip if already imported from its own file to avoid redeclaration.
    for req_iface in &class.required_interfaces {
        if req_iface.iid.is_empty() { continue; }
        if imported_names.contains(&req_iface.name) {
            // Already imported — re-exported automatically via the import
            continue;
        }
        let reg_var = format!("_{}", req_iface.name);
        out.push('\n');
        out.push_str(&format!("export class {} {{\n", req_iface.name));
        out.push_str("    readonly _obj: DynWinRtValue;\n\n");
        out.push_str("    constructor(obj: DynWinRtValue) {\n");
        out.push_str("        this._obj = obj;\n");
        out.push_str("    }\n\n");
        out.push_str(&format!(
            "    static from(obj: DynWinRtValue): {} {{\n",
            req_iface.name
        ));
        out.push_str(&format!(
            "        return new {}(obj.cast(IID_{}));\n",
            req_iface.name, req_iface.name
        ));
        out.push_str("    }\n");
        for method in &req_iface.methods {
            out.push('\n');
            out.push_str(&generate_iface_instance_method(req_iface, &reg_var, method, known_types, &delegate_type_names));
        }
        out.push_str("}\n");
    }
    out
}

// ======================================================================
// Method generation — invoke pattern
// ======================================================================

fn generate_factory_method_invoke(
    class: &ClassMeta,
    iface: &InterfaceMeta,
    method: &MethodMeta,
    known_types: &HashSet<String>,
) -> String {
    let in_params = get_in_params(method);
    let ts_params = ts_param_list(&in_params, known_types);

    let is_async = method.return_type.as_ref().is_some_and(|rt| rt.is_async());
    let return_ts_type = if is_async {
        format!("Promise<{}>", class.name)
    } else {
        class.name.clone()
    };

    let mut out = String::new();
    let async_kw = if is_async { "async " } else { "" };
    out.push_str(&format!(
        "    static {}{}({}): {} {{\n",
        async_kw, to_camel_case(&method.name), ts_params, return_ts_type
    ));

    let args_expr = build_args_expr(&in_params);
    let invoke_expr = format!(
        "_{iface}.method({idx}).invoke({cls}.f_{iface}(), [{args}])",
        iface = iface.name, idx = method.vtable_index, cls = class.name, args = args_expr
    );

    if is_async {
        out.push_str(&format!(
            "        return new {}(await {}.toPromise());\n",
            class.name, invoke_expr
        ));
    } else {
        out.push_str(&format!(
            "        return new {}({});\n",
            class.name, invoke_expr
        ));
    }
    out.push_str("    }\n");
    out
}

fn generate_static_method_invoke(
    class: &ClassMeta,
    iface: &InterfaceMeta,
    method: &MethodMeta,
    known_types: &HashSet<String>,
) -> String {
    let in_params = get_in_params(method);
    let ts_params = ts_param_list(&in_params, known_types);

    let return_type = method.return_type.as_ref();
    let is_with_progress = return_type.is_some_and(|rt| matches!(rt,
        TypeMeta::AsyncOperationWithProgress(_, _) | TypeMeta::AsyncActionWithProgress(_)));
    let is_async = return_type.is_some_and(|rt| rt.is_async()) && !is_with_progress;
    let ts_return = ts_return_type_safe(return_type, is_async, known_types);

    let mut out = String::new();

    let statics_call = format!("{cls}.s_{iface}()", cls = class.name, iface = iface.name);

    // Static property getter
    if method.is_property_getter && in_params.is_empty() {
        let prop_name = to_camel_case(method.name.strip_prefix("get_").unwrap_or(&method.name));
        out.push_str(&format!("    static get {}(): {} {{\n", prop_name, ts_return));
        let invoke_expr = format!(
            "_{}.method({}).invoke({}, [])",
            iface.name, method.vtable_index, statics_call
        );
        let converted = convert_return(&invoke_expr, return_type, false, known_types, &NO_DEFERRED);
        out.push_str(&format!("        return {};\n", converted));
        out.push_str("    }\n");
    } else {
        let async_kw = if is_async { "async " } else { "" };
        out.push_str(&format!(
            "    static {}{}({}): {} {{\n",
            async_kw, to_camel_case(&method.name), ts_params, ts_return
        ));
        let args_expr = build_args_expr(&in_params);
        let invoke_expr = format!(
            "_{}.method({}).invoke({}, [{}])",
            iface.name, method.vtable_index, statics_call, args_expr
        );
        if is_with_progress {
            let inner_type = match return_type {
                Some(TypeMeta::AsyncOperationWithProgress(inner, _)) => Some(inner.as_ref()),
                _ => None,
            };
            let inner_convert = convert_return("_v", inner_type, false, known_types, &NO_DEFERRED);
            out.push_str(&format!("        const _op = {};\n", invoke_expr));
            out.push_str(&format!("        const _promise = _op.toPromise().then((_v: DynWinRtValue) => {});\n", inner_convert));
            out.push_str(         "        return Object.assign(_promise, {\n");
            out.push_str(         "            progress(cb: (value: DynWinRtValue) => void) { _op.onProgress(cb); return this; },\n");
            out.push_str(&format!("            toPromise() {{ return _op.toPromise().then((_v: DynWinRtValue) => {}); }},\n", inner_convert));
            out.push_str(         "        });\n");
        } else {
            let converted = convert_return(&invoke_expr, return_type, is_async, known_types, &NO_DEFERRED);
            out.push_str(&format!("        return {};\n", converted));
        }
        out.push_str("    }\n");
    }
    out
}

/// Generate an instance method for an interface wrapper class.
/// Uses `_InterfaceName` as the registered interface variable and `this._obj` directly.
fn generate_iface_instance_method(
    _iface: &InterfaceMeta,
    iface_var: &str,
    method: &MethodMeta,
    known_types: &HashSet<String>,
    delegate_type_names: &HashSet<String>,
) -> String {
    generate_method_body(iface_var, "this._obj", method, known_types, delegate_type_names, None)
}

fn generate_method_body(
    iface_var: &str,
    obj_expr: &str,
    method: &MethodMeta,
    known_types: &HashSet<String>,
    delegate_type_names: &HashSet<String>,
    ts_name_override: Option<&str>,
) -> String {
    let in_params = get_in_params(method);
    let return_type = method.return_type.as_ref();
    let is_with_progress = return_type.is_some_and(|rt| matches!(rt,
        TypeMeta::AsyncOperationWithProgress(_, _) | TypeMeta::AsyncActionWithProgress(_)));
    let is_async = return_type.is_some_and(|rt| rt.is_async()) && !is_with_progress;
    // Methods with array out params (ReceiveArray/FillArray) return the array even without retval
    let has_array_out = method.params.iter().any(|p| {
        (p.direction == ParamDirection::Out || p.direction == ParamDirection::OutFill)
            && matches!(p.typ, TypeMeta::Array(_))
    });
    let has_return = return_type.is_some() || has_array_out;

    let mut out = String::new();

    // Event add: create delegate from JS callback, call add_, return token
    if method.is_event_add {
        let event_name = to_camel_case(method.name.strip_prefix("add_").unwrap_or(&method.name));
        // Get delegate name for IID and param types
        let delegate_name = in_params.first().and_then(|p| match &p.typ {
            TypeMeta::Parameterized { name, args, .. } =>
                Some(crate::meta::make_parameterized_name(name, args)),
            TypeMeta::Delegate { name, .. } => Some(name.clone()),
            _ => None,
        });
        out.push_str(&format!(
            "    on{}(callback: (...args: DynWinRtValue[]) => void): DynWinRtValue {{\n",
            capitalize(&event_name)
        ));
        if let Some(ref dname) = delegate_name {
            out.push_str(&format!(
                "        const handler = DynWinRtDelegate.create(IID_{}, {}_PARAM_TYPES, callback);\n",
                dname, dname
            ));
        } else {
            // Fallback: unknown delegate type, use object IID (may not work at runtime)
            out.push_str(
                "        const handler = DynWinRtDelegate.create(DynWinRtType.object().iid()!, [DynWinRtType.object(), DynWinRtType.object()], callback);\n"
            );
        }
        out.push_str(&format!(
            "        return {}.method({}).invoke({}, [handler.toValue()]);\n",
            iface_var, method.vtable_index, obj_expr
        ));
        out.push_str("    }\n");
        return out;
    }
    // Event remove: pass token to remove_
    if method.is_event_remove {
        let event_name = to_camel_case(method.name.strip_prefix("remove_").unwrap_or(&method.name));
        out.push_str(&format!(
            "    off{}(token: DynWinRtValue): void {{\n",
            capitalize(&event_name)
        ));
        out.push_str(&format!(
            "        {}.method({}).invoke({}, [token]);\n",
            iface_var, method.vtable_index, obj_expr
        ));
        out.push_str("    }\n");
        return out;
    }

    // Helper: check if a type refers to a delegate (needs DynWinRtValue, not class name)
    let is_delegate_type = |typ: Option<&TypeMeta>| -> bool {
        match typ {
            Some(TypeMeta::Delegate { .. }) => true,
            Some(TypeMeta::Interface { name, .. }) => delegate_type_names.contains(name),
            _ => false,
        }
    };

    if method.is_property_getter && in_params.is_empty() {
        // Property getter
        let prop_name = to_camel_case(method.name.strip_prefix("get_").unwrap_or(&method.name));
        let ts_return = if is_delegate_type(return_type) {
            "DynWinRtValue".to_string()
        } else {
            ts_return_type_safe(return_type, false, known_types)
        };
        out.push_str(&format!("    get {}(): {} {{\n", prop_name, ts_return));
        let invoke_expr = format!(
            "{}.method({}).invoke({}, [])",
            iface_var, method.vtable_index, obj_expr
        );
        let converted = if is_delegate_type(return_type) {
            invoke_expr.clone()
        } else {
            convert_return(&invoke_expr, return_type, false, known_types, &NO_DEFERRED)
        };
        out.push_str(&format!("        return {};\n", converted));
        out.push_str("    }\n");
    } else if method.is_property_setter {
        // Property setter
        let prop_name = to_camel_case(method.name.strip_prefix("put_").unwrap_or(&method.name));
        let param_type = if in_params.first().is_some_and(|p| is_delegate_type(Some(&p.typ))) {
            "DynWinRtValue".to_string()
        } else {
            in_params.first()
                .map(|p| ts_param_type_safe(&p.typ, known_types))
                .unwrap_or_else(|| "any".to_string())
        };
        out.push_str(&format!("    set {}(value: {}) {{\n", prop_name, param_type));
        let arg = in_params.first()
            .map(|p| wrap_arg("value", &p.typ))
            .unwrap_or_else(|| "value".to_string());
        out.push_str(&format!(
            "        {}.method({}).invoke({}, [{}]);\n",
            iface_var, method.vtable_index, obj_expr, arg
        ));
        out.push_str("    }\n");
    } else {
        // Regular method
        let ts_params = ts_param_list(&in_params, known_types);
        // For array out params, determine the element type for proper return type
        let array_out_elem = if has_array_out && return_type.is_none() {
            method.params.iter().find_map(|p| {
                if p.direction == ParamDirection::Out || p.direction == ParamDirection::OutFill {
                    if let TypeMeta::Array(inner) = &p.typ { Some(inner.as_ref()) } else { None }
                } else { None }
            })
        } else { None };
        let ts_return = if let Some(elem) = array_out_elem {
            ts_array_element_type(elem, known_types)
        } else {
            ts_return_type_safe(return_type, is_async, known_types)
        };
        let method_name = ts_name_override.map(|s| s.to_string()).unwrap_or_else(|| to_camel_case(&method.name));
        let async_kw = if is_async { "async " } else { "" };

        out.push_str(&format!(
            "    {}{}({}): {} {{\n",
            async_kw, method_name, ts_params, ts_return
        ));

        let args_expr = build_args_expr(&in_params);
        let invoke_expr = format!(
            "{}.method({}).invoke({}, [{}])",
            iface_var, method.vtable_index, obj_expr, args_expr
        );

        if is_with_progress {
            let inner_type = match return_type {
                Some(TypeMeta::AsyncOperationWithProgress(inner, _)) => Some(inner.as_ref()),
                _ => None,
            };
            let inner_convert = convert_return("_v", inner_type, false, known_types, &NO_DEFERRED);
            out.push_str(&format!("        const _op = {};\n", invoke_expr));
            out.push_str(&format!("        const _promise = _op.toPromise().then((_v: DynWinRtValue) => {});\n", inner_convert));
            out.push_str(         "        return Object.assign(_promise, {\n");
            out.push_str(         "            progress(cb: (value: DynWinRtValue) => void) { _op.onProgress(cb); return this; },\n");
            out.push_str(&format!("            toPromise() {{ return _op.toPromise().then((_v: DynWinRtValue) => {}); }},\n", inner_convert));
            out.push_str(         "        });\n");
        } else if !has_return && !is_async {
            out.push_str(&format!("        {};\n", invoke_expr));
        } else if is_async && matches!(return_type, Some(TypeMeta::AsyncAction) | Some(TypeMeta::AsyncActionWithProgress(_))) {
            // Async void: await without returning a value
            out.push_str(&format!("        await {}.toPromise();\n", invoke_expr));
        } else if let Some(elem) = array_out_elem {
            let arr_expr = format!("{}.asArray()", invoke_expr);
            let converted = convert_array_return(&arr_expr, elem, known_types, &NO_DEFERRED);
            out.push_str(&format!("        return {};\n", converted));
        } else {
            let converted = convert_return(&invoke_expr, return_type, is_async, known_types, &NO_DEFERRED);
            out.push_str(&format!("        return {};\n", converted));
        }
        out.push_str("    }\n");
    }

    out
}

/// TypeScript return type annotation for an array element type.
fn ts_array_element_type(inner: &TypeMeta, known_types: &HashSet<String>) -> String {
    match inner {
        TypeMeta::Bool => "boolean[]".to_string(),
        TypeMeta::String | TypeMeta::Guid => "string[]".to_string(),
        TypeMeta::I8 | TypeMeta::U8 | TypeMeta::I16 | TypeMeta::U16 | TypeMeta::Char16
        | TypeMeta::I32 | TypeMeta::U32 | TypeMeta::I64 | TypeMeta::U64
        | TypeMeta::F32 | TypeMeta::F64 | TypeMeta::Enum { .. } => "number[]".to_string(),
        TypeMeta::Struct { name, .. } if name == "HResult" => "number[]".to_string(),
        TypeMeta::Struct { name, .. } => format!("{}[]", name),
        TypeMeta::RuntimeClass { name, .. } if known_types.contains(name) => format!("{}[]", name),
        TypeMeta::Interface { name, .. } if known_types.contains(name) => format!("{}[]", name),
        _ => "DynWinRtValue[]".to_string(),
    }
}


// ======================================================================
// Helper: TypeScript type annotations
// ======================================================================

fn ts_param_type(typ: &TypeMeta) -> String {
    match typ {
        TypeMeta::Bool => "boolean".to_string(),
        TypeMeta::I8 | TypeMeta::U8 | TypeMeta::I16 | TypeMeta::U16 | TypeMeta::Char16
        | TypeMeta::I32 | TypeMeta::U32 | TypeMeta::I64 | TypeMeta::U64
        | TypeMeta::F32 | TypeMeta::F64 => {
            "number".to_string()
        }
        TypeMeta::String | TypeMeta::Guid => "string".to_string(),
        TypeMeta::RuntimeClass { name, .. }
        | TypeMeta::Enum { name, .. }
        | TypeMeta::Interface { name, .. } => name.clone(),
        TypeMeta::Parameterized { name, args, .. } => crate::meta::make_parameterized_name(name, args),
        TypeMeta::Array(_) => "DynWinRtArray".to_string(),
        TypeMeta::Object | TypeMeta::Delegate { .. } => "DynWinRtValue".to_string(),
        TypeMeta::Struct { name, .. } if name == "HResult" => "number".to_string(),
        TypeMeta::Struct { name, .. } => name.clone(),
        _ => "any".to_string(),
    }
}

fn ts_param_type_safe(typ: &TypeMeta, known: &HashSet<String>) -> String {
    match typ {
        TypeMeta::RuntimeClass { name, .. }
        | TypeMeta::Enum { name, .. }
        | TypeMeta::Interface { name, .. } if !known.contains(name) => "DynWinRtValue".to_string(),
        _ => ts_param_type(typ),
    }
}

fn ts_return_type_safe(typ: Option<&TypeMeta>, is_async: bool, known: &HashSet<String>) -> String {
    match typ {
        Some(TypeMeta::RuntimeClass { name, .. })
        | Some(TypeMeta::Enum { name, .. })
        | Some(TypeMeta::Interface { name, .. }) if !known.contains(name) => {
            if is_async { "Promise<DynWinRtValue>".to_string() } else { "DynWinRtValue".to_string() }
        }
        Some(TypeMeta::AsyncOperation(inner)) => {
            format!("Promise<{}>", ts_return_type_safe(Some(inner), false, known))
        }
        Some(TypeMeta::AsyncOperationWithProgress(result, _)) => {
            let inner = ts_return_type_safe(Some(result), false, known);
            format!("Promise<{i}> & {{ progress(cb: (value: DynWinRtValue) => void): Promise<{i}> & {{ progress: any; toPromise(): Promise<{i}>; }}; toPromise(): Promise<{i}>; }}", i = inner)
        }
        Some(TypeMeta::AsyncActionWithProgress(_)) => {
            "Promise<void> & { progress(cb: (value: DynWinRtValue) => void): Promise<void> & { progress: any; toPromise(): Promise<void>; }; toPromise(): Promise<void>; }".to_string()
        }
        Some(TypeMeta::Array(inner)) => {
            let s = ts_array_element_type(inner, known);
            if is_async { format!("Promise<{}>", s) } else { s }
        }
        _ => ts_return_type(typ, is_async),
    }
}

fn ts_return_type(typ: Option<&TypeMeta>, is_async: bool) -> String {
    let inner = match typ {
        Some(TypeMeta::String) | Some(TypeMeta::Guid) => "string",
        Some(TypeMeta::Bool) => "boolean",
        Some(TypeMeta::I8 | TypeMeta::U8 | TypeMeta::I16 | TypeMeta::U16 | TypeMeta::Char16
            | TypeMeta::I32 | TypeMeta::U32 | TypeMeta::I64 | TypeMeta::U64
            | TypeMeta::F32 | TypeMeta::F64) => "number",
        Some(TypeMeta::RuntimeClass { name, .. }) => {
            return if is_async { format!("Promise<{}>", name) } else { name.clone() }
        }
        Some(TypeMeta::Enum { name, .. }) => {
            return if is_async { format!("Promise<{}>", name) } else { name.clone() }
        }
        Some(TypeMeta::Interface { name, .. }) => {
            return if is_async { format!("Promise<{}>", name) } else { name.clone() }
        }
        Some(TypeMeta::Parameterized { name, args, .. }) => {
            let s = crate::meta::make_parameterized_name(name, args);
            return if is_async { format!("Promise<{}>", s) } else { s };
        }
        Some(TypeMeta::AsyncOperation(inner)) => {
            return format!("Promise<{}>", ts_return_type(Some(inner), false));
        }
        Some(TypeMeta::AsyncOperationWithProgress(result, _)) => {
            let inner = ts_return_type(Some(result), false);
            return format!("Promise<{i}> & {{ progress(cb: (value: DynWinRtValue) => void): Promise<{i}> & {{ progress: any; toPromise(): Promise<{i}>; }}; toPromise(): Promise<{i}>; }}", i = inner);
        }
        Some(TypeMeta::AsyncAction) => return "Promise<void>".to_string(),
        Some(TypeMeta::AsyncActionWithProgress(_)) => {
            return "Promise<void> & { progress(cb: (value: DynWinRtValue) => void): Promise<void> & { progress: any; toPromise(): Promise<void>; }; toPromise(): Promise<void>; }".to_string();
        }
        Some(TypeMeta::Array(inner)) => {
            let s = ts_array_element_type(inner, &HashSet::new());
            return if is_async { format!("Promise<{}>", s) } else { s };
        }
        Some(TypeMeta::Object) | Some(TypeMeta::Delegate { .. }) => "DynWinRtValue",
        Some(TypeMeta::Struct { name, .. }) if name == "HResult" => "number",
        Some(TypeMeta::Struct { name, .. }) => {
            return if is_async { format!("Promise<{}>", name) } else { name.clone() }
        }
        None => "void",
    };
    if is_async { format!("Promise<{}>", inner) } else { inner.to_string() }
}

/// Format an import line based on type kind.
/// - Interfaces export both IID and wrapper class
/// - Classes and enums only export the name (IIDs are internal)
fn format_type_import(name: &str, kind: &str) -> String {
    if kind == "interface" {
        format!("import {{ IID_{name}, {name} }} from './{name}.js';\n")
    } else {
        format!("import {{ {} }} from './{}';\n", name, name)
    }
}

fn ts_param_list(in_params: &[&crate::meta::ParamMeta], known_types: &HashSet<String>) -> String {
    in_params.iter()
        .map(|p| format!("{}: {}", to_camel_case(&p.name), ts_param_type_safe(&p.typ, known_types)))
        .collect::<Vec<_>>()
        .join(", ")
}

