use std::collections::{HashMap, HashSet};

use crate::meta::{ClassMeta, InterfaceMeta, MethodMeta, ParamDirection};
use crate::types::TypeMeta;

// ======================================================================
// Public entry points
// ======================================================================

// Well-known generic collection interface short names (from Windows.Foundation.Collections)
const KNOWN_GENERICS: &[(&str, &str, u8)] = &[
    ("IIterable`1", "IIterable", 1),
    ("IIterator`1", "IIterator", 1),
    ("IVectorView`1", "IVectorView", 1),
    ("IVector`1", "IVector", 1),
    ("IMapView`2", "IMapView", 2),
    ("IMap`2", "IMap", 2),
    ("IKeyValuePair`2", "IKeyValuePair", 2),
    ("IObservableVector`1", "IObservableVector", 1),
    ("IObservableMap`2", "IObservableMap", 2),
];

/// Map a Parameterized type name to its short generic TS name, if known.
fn known_generic_name(name: &str) -> Option<&'static str> {
    KNOWN_GENERICS.iter().find(|(n, _, _)| *n == name).map(|(_, short, _)| *short)
}

/// Format a Parameterized type as a TS generic type string, e.g. "IVectorView<string>".
fn ts_parameterized_type(name: &str, args: &[TypeMeta]) -> String {
    if let Some(short) = known_generic_name(name) {
        let ts_args: Vec<String> = args.iter().map(|a| ts_param_type(a)).collect();
        format!("{}<{}>", short, ts_args.join(", "))
    } else {
        "DynWinRtValue".to_string()
    }
}

/// Generate _collections.ts with generic wrapper classes for well-known WinRT collection interfaces.
pub fn generate_collections() -> String {
    r#"// Generated by winrt-meta — do not edit
// Well-known WinRT generic collection interfaces using registerInterface + invoke
import { DynWinRtType, DynWinRtMethodSig, DynWinRtValue, DynWinRtArray, DynWinRtDelegate, WinGuid } from 'dynwinrt-js';

// PIIDs for parameterized collection interfaces
const PIID_IIterable = WinGuid.parse('faa585ea-6214-4217-afda-7f46de5869b3');
const PIID_IIterator = WinGuid.parse('6a79e863-4300-459a-9966-cbb660963ee1');
const PIID_IVectorView = WinGuid.parse('bbe1fa4c-b0e3-4583-baef-1f1b2e483e56');
const PIID_IVector = WinGuid.parse('913337e9-11a1-4345-a3a2-4e7f956e222d');
const PIID_IMapView = WinGuid.parse('e480ce40-a338-4ada-adcf-272272e48cb9');
const PIID_IMap = WinGuid.parse('3c2925fe-8519-45c1-aa79-197b6718c1c1');
const PIID_IKeyValuePair = WinGuid.parse('02b51929-c1c4-4a7e-8940-0312b5c18500');

// Cache registered interfaces by parameterized IID string to avoid re-registration
const _cache = new Map<string, DynWinRtType>();

function _reg(name: string, piid: WinGuid, tArgs: DynWinRtType[], setup: (iface: DynWinRtType) => DynWinRtType): DynWinRtType {
    const pType = DynWinRtType.parameterized(piid, tArgs);
    const iid = pType.iid();
    const key = iid.toString();
    let cached = _cache.get(key);
    if (cached) return cached;
    cached = setup(DynWinRtType.registerInterface(name + '_' + key, iid));
    _cache.set(key, cached);
    return cached;
}

export class IIterable<T> {
    readonly _obj: DynWinRtValue;
    private _iface: DynWinRtType;
    constructor(obj: DynWinRtValue, private _t: DynWinRtType = DynWinRtType.object()) {
        this._obj = obj;
        this._iface = _reg('IIterable', PIID_IIterable, [_t], i => i
            .addMethod("First", new DynWinRtMethodSig().addOut(DynWinRtType.object())));
    }
    first(): IIterator<T> { return new IIterator<T>(this._iface.method(6).invoke(this._obj, []), this._t); }
}

export class IIterator<T> {
    readonly _obj: DynWinRtValue;
    private _iface: DynWinRtType;
    constructor(obj: DynWinRtValue, private _t: DynWinRtType = DynWinRtType.object()) {
        this._obj = obj;
        this._iface = _reg('IIterator', PIID_IIterator, [_t], i => i
            .addMethod("get_Current", new DynWinRtMethodSig().addOut(_t))
            .addMethod("get_HasCurrent", new DynWinRtMethodSig().addOut(DynWinRtType.boolType()))
            .addMethod("MoveNext", new DynWinRtMethodSig().addOut(DynWinRtType.boolType())));
    }
    get current(): DynWinRtValue { return this._iface.method(6).invoke(this._obj, []); }
    get hasCurrent(): boolean { return this._iface.method(7).invoke(this._obj, []).toNumber() !== 0; }
    moveNext(): boolean { return this._iface.method(8).invoke(this._obj, []).toNumber() !== 0; }
}

export class IVectorView<T> {
    readonly _obj: DynWinRtValue;
    private _iface: DynWinRtType;
    constructor(obj: DynWinRtValue, private _t: DynWinRtType = DynWinRtType.object()) {
        this._obj = obj;
        this._iface = _reg('IVectorView', PIID_IVectorView, [_t], i => i
            .addMethod("GetAt", new DynWinRtMethodSig().addIn(DynWinRtType.u32()).addOut(_t))
            .addMethod("get_Size", new DynWinRtMethodSig().addOut(DynWinRtType.u32())));
    }
    getAt(index: number): DynWinRtValue { return this._iface.method(6).invoke(this._obj, [DynWinRtValue.i32(index)]); }
    get size(): number { return this._iface.method(7).invoke(this._obj, []).toNumber(); }
}

export class IVector<T> {
    readonly _obj: DynWinRtValue;
    private _iface: DynWinRtType;
    constructor(obj: DynWinRtValue, private _t: DynWinRtType = DynWinRtType.object()) {
        this._obj = obj;
        this._iface = _reg('IVector', PIID_IVector, [_t], i => i
            .addMethod("GetAt", new DynWinRtMethodSig().addIn(DynWinRtType.u32()).addOut(_t))
            .addMethod("get_Size", new DynWinRtMethodSig().addOut(DynWinRtType.u32()))
            .addMethod("GetView", new DynWinRtMethodSig().addOut(DynWinRtType.object()))
            .addMethod("IndexOf", new DynWinRtMethodSig().addIn(_t).addOut(DynWinRtType.u32()).addOut(DynWinRtType.boolType()))
            .addMethod("SetAt", new DynWinRtMethodSig().addIn(DynWinRtType.u32()).addIn(_t))
            .addMethod("InsertAt", new DynWinRtMethodSig().addIn(DynWinRtType.u32()).addIn(_t))
            .addMethod("RemoveAt", new DynWinRtMethodSig().addIn(DynWinRtType.u32()))
            .addMethod("Append", new DynWinRtMethodSig().addIn(_t))
            .addMethod("RemoveAtEnd", new DynWinRtMethodSig())
            .addMethod("Clear", new DynWinRtMethodSig()));
    }
    getAt(index: number): DynWinRtValue { return this._iface.method(6).invoke(this._obj, [DynWinRtValue.i32(index)]); }
    get size(): number { return this._iface.method(7).invoke(this._obj, []).toNumber(); }
    getView(): IVectorView<T> { return new IVectorView<T>(this._iface.method(8).invoke(this._obj, []), this._t); }
    setAt(index: number, value: DynWinRtValue): void { this._iface.method(10).invoke(this._obj, [DynWinRtValue.i32(index), value]); }
    insertAt(index: number, value: DynWinRtValue): void { this._iface.method(11).invoke(this._obj, [DynWinRtValue.i32(index), value]); }
    removeAt(index: number): void { this._iface.method(12).invoke(this._obj, [DynWinRtValue.i32(index)]); }
    append(value: DynWinRtValue): void { this._iface.method(13).invoke(this._obj, [value]); }
    removeAtEnd(): void { this._iface.method(14).invoke(this._obj, []); }
    clear(): void { this._iface.method(15).invoke(this._obj, []); }
}

export class IMapView<K, V> {
    readonly _obj: DynWinRtValue;
    private _iface: DynWinRtType;
    constructor(obj: DynWinRtValue, private _k: DynWinRtType = DynWinRtType.object(), private _v: DynWinRtType = DynWinRtType.object()) {
        this._obj = obj;
        this._iface = _reg('IMapView', PIID_IMapView, [_k, _v], i => i
            .addMethod("Lookup", new DynWinRtMethodSig().addIn(_k).addOut(_v))
            .addMethod("get_Size", new DynWinRtMethodSig().addOut(DynWinRtType.u32()))
            .addMethod("HasKey", new DynWinRtMethodSig().addIn(_k).addOut(DynWinRtType.boolType())));
    }
    lookup(key: DynWinRtValue): DynWinRtValue { return this._iface.method(6).invoke(this._obj, [key]); }
    get size(): number { return this._iface.method(7).invoke(this._obj, []).toNumber(); }
    hasKey(key: DynWinRtValue): boolean { return this._iface.method(8).invoke(this._obj, [key]).toNumber() !== 0; }
}

export class IMap<K, V> {
    readonly _obj: DynWinRtValue;
    private _iface: DynWinRtType;
    constructor(obj: DynWinRtValue, private _k: DynWinRtType = DynWinRtType.object(), private _v: DynWinRtType = DynWinRtType.object()) {
        this._obj = obj;
        this._iface = _reg('IMap', PIID_IMap, [_k, _v], i => i
            .addMethod("Lookup", new DynWinRtMethodSig().addIn(_k).addOut(_v))
            .addMethod("get_Size", new DynWinRtMethodSig().addOut(DynWinRtType.u32()))
            .addMethod("HasKey", new DynWinRtMethodSig().addIn(_k).addOut(DynWinRtType.boolType()))
            .addMethod("GetView", new DynWinRtMethodSig().addOut(DynWinRtType.object()))
            .addMethod("Insert", new DynWinRtMethodSig().addIn(_k).addIn(_v).addOut(DynWinRtType.boolType()))
            .addMethod("Remove", new DynWinRtMethodSig().addIn(_k))
            .addMethod("Clear", new DynWinRtMethodSig()));
    }
    lookup(key: DynWinRtValue): DynWinRtValue { return this._iface.method(6).invoke(this._obj, [key]); }
    get size(): number { return this._iface.method(7).invoke(this._obj, []).toNumber(); }
    hasKey(key: DynWinRtValue): boolean { return this._iface.method(8).invoke(this._obj, [key]).toNumber() !== 0; }
    getView(): IMapView<K, V> { return new IMapView<K, V>(this._iface.method(9).invoke(this._obj, []), this._k, this._v); }
    insert(key: DynWinRtValue, value: DynWinRtValue): boolean { return this._iface.method(10).invoke(this._obj, [key, value]).toNumber() !== 0; }
    remove(key: DynWinRtValue): void { this._iface.method(11).invoke(this._obj, [key]); }
    clear(): void { this._iface.method(12).invoke(this._obj, []); }
}

export class IKeyValuePair<K, V> {
    readonly _obj: DynWinRtValue;
    private _iface: DynWinRtType;
    constructor(obj: DynWinRtValue, private _k: DynWinRtType = DynWinRtType.object(), private _v: DynWinRtType = DynWinRtType.object()) {
        this._obj = obj;
        this._iface = _reg('IKeyValuePair', PIID_IKeyValuePair, [_k, _v], i => i
            .addMethod("get_Key", new DynWinRtMethodSig().addOut(_k))
            .addMethod("get_Value", new DynWinRtMethodSig().addOut(_v)));
    }
    get key(): DynWinRtValue { return this._iface.method(6).invoke(this._obj, []); }
    get value(): DynWinRtValue { return this._iface.method(7).invoke(this._obj, []); }
}

export class IObservableVector<T> {
    readonly _obj: DynWinRtValue;
    constructor(obj: DynWinRtValue, private _t: DynWinRtType = DynWinRtType.object()) { this._obj = obj; }
}

export class IObservableMap<K, V> {
    readonly _obj: DynWinRtValue;
    constructor(obj: DynWinRtValue, private _k: DynWinRtType = DynWinRtType.object(), private _v: DynWinRtType = DynWinRtType.object()) { this._obj = obj; }
}
"#.to_string()
}

/// Check if any type in the tree uses a known generic collection type.
pub fn uses_collections(classes: &[ClassMeta], interfaces: &[InterfaceMeta]) -> bool {
    fn check_type(typ: &TypeMeta) -> bool {
        match typ {
            TypeMeta::Parameterized { name, .. } => known_generic_name(name).is_some(),
            TypeMeta::AsyncOperation(inner) | TypeMeta::AsyncActionWithProgress(inner) => check_type(inner),
            TypeMeta::AsyncOperationWithProgress(r, p) => check_type(r) || check_type(p),
            TypeMeta::Array(inner) => check_type(inner),
            _ => false,
        }
    }
    fn check_methods(methods: &[MethodMeta]) -> bool {
        methods.iter().any(|m| {
            m.params.iter().any(|p| check_type(&p.typ))
                || m.return_type.as_ref().is_some_and(|rt| check_type(rt))
        })
    }
    for c in classes {
        if let Some(ref iface) = c.default_interface {
            if check_methods(&iface.methods) { return true; }
        }
        for iface in &c.factory_interfaces { if check_methods(&iface.methods) { return true; } }
        for iface in &c.static_interfaces { if check_methods(&iface.methods) { return true; } }
    }
    for i in interfaces {
        if check_methods(&i.methods) { return true; }
    }
    false
}

/// Generate an index.ts that re-exports all generated types.
pub fn generate_index(classes: &[ClassMeta], interfaces: &[InterfaceMeta], enums: &[TypeMeta]) -> String {
    let mut out = String::new();
    out.push_str("// Generated by winrt-meta — do not edit\n");
    for class in classes {
        out.push_str(&format!("export {{ {} }} from './{}';\n", class.name, class.name));
    }
    for iface in interfaces {
        let is_delegate = iface.methods.iter().any(|m| m.name == ".ctor")
            && iface.methods.iter().any(|m| m.name == "Invoke");
        if is_delegate {
            out.push_str(&format!(
                "export {{ IID_{iname}, {iname}_PARAM_TYPES }} from './{iname}';\n",
                iname = iface.name
            ));
        } else {
            out.push_str(&format!(
                "export {{ IID_{iname}, {iname} }} from './{iname}';\n",
                iname = iface.name
            ));
        }
    }
    for en in enums {
        if let TypeMeta::Enum { name, .. } = en {
            out.push_str(&format!("export {{ {} }} from './{}';\n", name, name));
        }
    }
    out
}

/// Generate a TypeScript file for a single enum.
pub fn generate_enum(en: &TypeMeta) -> Option<String> {
    let (name, members) = match en {
        TypeMeta::Enum { name, members, .. } => (name, members),
        _ => return None,
    };

    let mut out = String::new();
    out.push_str("// Generated by winrt-meta — do not edit\n\n");
    out.push_str(&format!("export enum {} {{\n", name));
    for member in members {
        out.push_str(&format!("    {} = {},\n", member.name, member.value));
    }
    out.push_str("}\n");
    Some(out)
}

/// Generate a TypeScript file for a WinRT interface (non-exclusive).
/// Outputs IID, registerInterface, and a wrapper class with typed methods.
pub fn generate_interface(iface: &InterfaceMeta, known_types: &HashSet<String>, delegate_type_names: &HashSet<String>) -> String {
    // Detect delegate types (have .ctor + Invoke methods)
    let is_delegate = iface.methods.iter().any(|m| m.name == ".ctor")
        && iface.methods.iter().any(|m| m.name == "Invoke");
    if is_delegate {
        return generate_delegate(iface);
    }

    // Collect structs used in interface methods
    let used_structs = collect_used_structs_from_iface(iface);
    let has_structs = !used_structs.is_empty();

    let mut out = String::new();
    out.push_str("// Generated by winrt-meta — do not edit\n");
    if has_structs {
        out.push_str("import { DynWinRtType, DynWinRtMethodSig, DynWinRtValue, DynWinRtArray, DynWinRtStruct, DynWinRtDelegate, WinGuid } from 'dynwinrt-js';\n");
    } else {
        out.push_str("import { DynWinRtType, DynWinRtMethodSig, DynWinRtValue, DynWinRtArray, DynWinRtDelegate, WinGuid } from 'dynwinrt-js';\n");
    }
    // Collect delegate names — delegates don't export classes, only IID + PARAM_TYPES
    let mut delegate_names: HashSet<String> = delegate_type_names.clone();
    for method in &iface.methods {
        for p in &method.params {
            match &p.typ {
                TypeMeta::Delegate { name, .. } => { delegate_names.insert(name.clone()); }
                _ => {}
            }
            // Parameterized delegates used in event add/setter methods
            if method.is_event_add || method.is_event_remove || method.name.starts_with("put_") {
                if let TypeMeta::Parameterized { name, args, .. } = &p.typ {
                    delegate_names.insert(crate::meta::make_parameterized_name(name, args));
                }
            }
        }
    }

    // Import parameterized collection types (skip delegates — they don't export classes)
    let collection_names = collect_used_generics_from_methods(&iface.methods);
    for cname in &collection_names {
        if cname != &iface.name && !delegate_names.contains(cname) {
            out.push_str(&format!("import {{ {} }} from './{}';\n", cname, cname));
        }
    }

    // Import delegate IID + PARAM_TYPES for event methods
    for dname in &delegate_names {
        out.push_str(&format!(
            "import {{ IID_{dname}, {dname}_PARAM_TYPES }} from './{dname}';\n",
        ));
    }

    // Type imports for referenced types (enums, classes, other interfaces)
    // Skip delegate names — they don't export classes, only IID + PARAM_TYPES
    let type_imports = collect_iface_type_imports(iface);
    for (_ns, name, kind) in &type_imports {
        if known_types.contains(name) && !delegate_names.contains(name) {
            out.push_str(&format_type_import(name, kind));
        }
    }
    out.push('\n');

    // IID constant — for parameterized interfaces, compute from PIID + type args
    if let Some(ref piid) = iface.generic_piid {
        let args_ts: Vec<String> = iface.generic_args.iter().map(|a| ts_dynwinrt_type(a)).collect();
        out.push_str(&format!(
            "export const IID_{} = DynWinRtType.parameterized(WinGuid.parse('{}'), [{}]).iid()!;\n\n",
            iface.name, piid, args_ts.join(", ")
        ));
    } else if !iface.iid.is_empty() {
        out.push_str(&format!(
            "export const IID_{} = WinGuid.parse('{}');\n\n",
            iface.name, iface.iid
        ));
    }

    // Interface registration (private const, used by wrapper class)
    out.push_str(&format!("const _{} = DynWinRtType.registerInterface(\n", iface.name));
    out.push_str(&format!("    \"{}\", IID_{})\n", iface.name, iface.name));

    for method in &iface.methods {
        out.push_str(&format!(
            "    .addMethod(\"{}\", {})\n",
            method.name,
            build_method_sig(method)
        ));
    }
    trim_trailing_newline_add_semicolon(&mut out);
    out.push('\n');

    // Struct interface + unpack/pack helpers
    for s in &used_structs {
        out.push_str(&generate_struct_helpers(s));
        out.push('\n');
    }

    // Wrapper class
    out.push_str(&format!("export class {} {{\n", iface.name));
    out.push_str("    readonly _obj: DynWinRtValue;\n\n");
    if iface.generic_piid.is_some() {
        // Parameterized interfaces need QI cast in constructor
        out.push_str("    constructor(obj: DynWinRtValue) {\n");
        out.push_str(&format!("        this._obj = obj.cast(IID_{});\n", iface.name));
        out.push_str("    }\n");
    } else {
        out.push_str("    constructor(obj: DynWinRtValue) {\n");
        out.push_str("        this._obj = obj;\n");
        out.push_str("    }\n");
    }

    // static from() — QI cast
    if !iface.iid.is_empty() {
        out.push('\n');
        out.push_str(&format!(
            "    static from(obj: DynWinRtValue): {} {{\n",
            iface.name
        ));
        out.push_str(&format!(
            "        return new {}(obj.cast(IID_{}));\n",
            iface.name, iface.name
        ));
        out.push_str("    }\n");
    }

    // Instance methods
    let iface_var = format!("_{}", iface.name);
    for method in &iface.methods {
        out.push('\n');
        out.push_str(&generate_iface_instance_method(iface, &iface_var, method, known_types, &delegate_type_names));
    }

    out.push_str("}\n");
    out
}

/// Generate a TypeScript file for a delegate type.
/// Exports the IID constant and Invoke param types for use with DynWinRtDelegate.create().
fn generate_delegate(iface: &InterfaceMeta) -> String {
    let mut out = String::new();
    out.push_str("// Generated by winrt-meta — do not edit (delegate)\n");
    out.push_str("import { DynWinRtType, WinGuid } from 'dynwinrt-js';\n\n");

    // Export IID — compute from piid + Invoke param types at load time
    let invoke = iface.methods.iter().find(|m| m.name == "Invoke");
    let param_exprs: Vec<String> = invoke.map(|inv| {
        inv.params.iter()
            .filter(|p| p.direction == ParamDirection::In)
            .map(|p| ts_dynwinrt_type(&p.typ))
            .collect()
    }).unwrap_or_default();

    if !iface.iid.is_empty() {
        out.push_str(&format!(
            "export const IID_{} = DynWinRtType.parameterized(WinGuid.parse('{}'), [{}]).iid()!;\n",
            iface.name, iface.iid, param_exprs.join(", ")
        ));
    } else {
        out.push_str(&format!(
            "export const IID_{}: any = undefined;\n",
            iface.name
        ));
    }

    // Export Invoke param types as an array for DynWinRtDelegate.create()
    let invoke = iface.methods.iter().find(|m| m.name == "Invoke");
    if let Some(invoke) = invoke {
        let param_exprs: Vec<String> = invoke.params.iter()
            .filter(|p| p.direction == ParamDirection::In)
            .map(|p| ts_dynwinrt_type(&p.typ))
            .collect();
        out.push_str(&format!(
            "export const {}_PARAM_TYPES = [{}];\n",
            iface.name,
            param_exprs.join(", ")
        ));
    }

    out
}

// ======================================================================
// Struct helpers: TS interface + _unpack/_pack functions
// ======================================================================

/// Recursively collect non-HResult struct types from a type tree.
fn collect_used_structs_from_type(typ: &TypeMeta, seen: &mut HashSet<String>, result: &mut Vec<TypeMeta>) {
    match typ {
        TypeMeta::Struct { namespace, name, fields } => {
            if name != "HResult" {
                let full = format!("{}.{}", namespace, name);
                if !seen.insert(full) {
                    return; // already collected
                }
            }
            // Recurse into fields FIRST so nested structs appear before this one
            for f in fields { collect_used_structs_from_type(&f.typ, seen, result); }
            if name != "HResult" {
                result.push(typ.clone());
            }
        }
        TypeMeta::AsyncOperation(inner) | TypeMeta::AsyncActionWithProgress(inner) => {
            collect_used_structs_from_type(inner, seen, result);
        }
        TypeMeta::AsyncOperationWithProgress(r, p) => {
            collect_used_structs_from_type(r, seen, result);
            collect_used_structs_from_type(p, seen, result);
        }
        TypeMeta::Array(inner) => collect_used_structs_from_type(inner, seen, result),
        TypeMeta::Parameterized { args, .. } => {
            for arg in args { collect_used_structs_from_type(arg, seen, result); }
        }
        _ => {}
    }
}

fn collect_used_structs_from_class(class: &ClassMeta) -> Vec<TypeMeta> {
    let mut seen = HashSet::new();
    let mut result = Vec::new();
    fn visit_methods(methods: &[MethodMeta], seen: &mut HashSet<String>, result: &mut Vec<TypeMeta>) {
        for m in methods {
            for p in &m.params { collect_used_structs_from_type(&p.typ, seen, result); }
            if let Some(ref rt) = m.return_type { collect_used_structs_from_type(rt, seen, result); }
        }
    }
    if let Some(ref iface) = class.default_interface { visit_methods(&iface.methods, &mut seen, &mut result); }
    for iface in &class.factory_interfaces { visit_methods(&iface.methods, &mut seen, &mut result); }
    for iface in &class.static_interfaces { visit_methods(&iface.methods, &mut seen, &mut result); }
    for iface in &class.required_interfaces { visit_methods(&iface.methods, &mut seen, &mut result); }
    result
}

fn collect_used_structs_from_iface(iface: &InterfaceMeta) -> Vec<TypeMeta> {
    let mut seen = HashSet::new();
    let mut result = Vec::new();
    for m in &iface.methods {
        for p in &m.params { collect_used_structs_from_type(&p.typ, &mut seen, &mut result); }
        if let Some(ref rt) = m.return_type { collect_used_structs_from_type(rt, &mut seen, &mut result); }
    }
    result
}

/// Map a struct field type to its TypeScript type annotation.
fn ts_struct_field_type(typ: &TypeMeta) -> String {
    match typ {
        TypeMeta::Bool => "boolean".to_string(),
        TypeMeta::String => "string".to_string(),
        TypeMeta::Guid => "string".to_string(),
        TypeMeta::I8 | TypeMeta::U8 | TypeMeta::I16 | TypeMeta::U16 | TypeMeta::Char16
        | TypeMeta::I32 | TypeMeta::U32 | TypeMeta::I64 | TypeMeta::U64
        | TypeMeta::F32 | TypeMeta::F64 | TypeMeta::Enum { .. } => "number".to_string(),
        TypeMeta::Struct { name, .. } if name == "HResult" => "number".to_string(),
        TypeMeta::Struct { name, .. } => name.clone(),
        _ => "DynWinRtValue".to_string(),
    }
}

/// Generate a `DynWinRtStruct.getXxx(index)` expression for a struct field.
fn struct_field_getter(typ: &TypeMeta, index: usize) -> String {
    match typ {
        TypeMeta::Bool => format!("s.getU8({}) !== 0", index),
        TypeMeta::I8 => format!("s.getI8({})", index),
        TypeMeta::U8 => format!("s.getU8({})", index),
        TypeMeta::I16 => format!("s.getI16({})", index),
        TypeMeta::U16 | TypeMeta::Char16 => format!("s.getU16({})", index),
        TypeMeta::I32 | TypeMeta::Enum { .. } => format!("s.getI32({})", index),
        TypeMeta::U32 => format!("s.getU32({})", index),
        TypeMeta::I64 => format!("s.getI64({})", index),
        TypeMeta::U64 => format!("s.getU64({})", index),
        TypeMeta::F32 => format!("s.getF32({})", index),
        TypeMeta::F64 => format!("s.getF64({})", index),
        TypeMeta::String => format!("s.getHstring({})", index),
        TypeMeta::Guid => format!("s.getGuid({}).toString()", index),
        TypeMeta::Struct { name, .. } if name == "HResult" => format!("s.getI32({})", index),
        TypeMeta::Struct { name, .. } => format!("_unpack{}(s.getStruct({}).toValue())", name, index),
        _ => format!("s.getObject({})", index), // IReference<T> etc.
    }
}

/// Generate a `s.setXxx(index, expr)` statement for a struct field.
fn struct_field_setter(typ: &TypeMeta, index: usize, value_expr: &str) -> String {
    match typ {
        TypeMeta::Bool => format!("s.setU8({}, {} ? 1 : 0)", index, value_expr),
        TypeMeta::I8 => format!("s.setI8({}, {})", index, value_expr),
        TypeMeta::U8 => format!("s.setU8({}, {})", index, value_expr),
        TypeMeta::I16 => format!("s.setI16({}, {})", index, value_expr),
        TypeMeta::U16 | TypeMeta::Char16 => format!("s.setU16({}, {})", index, value_expr),
        TypeMeta::I32 | TypeMeta::Enum { .. } => format!("s.setI32({}, {})", index, value_expr),
        TypeMeta::U32 => format!("s.setU32({}, {})", index, value_expr),
        TypeMeta::I64 => format!("s.setI64({}, {})", index, value_expr),
        TypeMeta::U64 => format!("s.setU64({}, {})", index, value_expr),
        TypeMeta::F32 => format!("s.setF32({}, {})", index, value_expr),
        TypeMeta::F64 => format!("s.setF64({}, {})", index, value_expr),
        TypeMeta::String => format!("s.setHstring({}, {})", index, value_expr),
        TypeMeta::Guid => format!("s.setGuid({}, WinGuid.parse({}))", index, value_expr),
        TypeMeta::Struct { name, .. } if name == "HResult" => format!("s.setI32({}, {})", index, value_expr),
        TypeMeta::Struct { name, .. } => format!("s.setStruct({}, _pack{}({}))", index, name, value_expr),
        _ => format!("s.setObject({}, {})", index, value_expr), // IReference<T> etc.
    }
}

/// Generate TS interface + _unpack/_pack helpers for a single struct type.
fn generate_struct_helpers(s: &TypeMeta) -> String {
    let (namespace, name, fields) = match s {
        TypeMeta::Struct { namespace, name, fields } => (namespace, name, fields),
        _ => return String::new(),
    };
    let mut out = String::new();

    // TS interface
    out.push_str(&format!("interface {} {{\n", name));
    for f in fields {
        out.push_str(&format!("    {}: {};\n", to_camel_case(&f.name), ts_struct_field_type(&f.typ)));
    }
    out.push_str("}\n");

    // _unpack function: DynWinRtValue → plain JS object
    out.push_str(&format!("function _unpack{}(v: DynWinRtValue): {} {{\n", name, name));
    out.push_str("    const s = v.asStruct();\n");
    out.push_str("    return { ");
    let field_exprs: Vec<String> = fields.iter().enumerate().map(|(i, f)| {
        format!("{}: {}", to_camel_case(&f.name), struct_field_getter(&f.typ, i))
    }).collect();
    out.push_str(&field_exprs.join(", "));
    out.push_str(" };\n");
    out.push_str("}\n");

    // Type constant for _pack
    let full_name = format!("{}.{}", namespace, name);
    let field_types: Vec<String> = fields.iter().map(|f| ts_dynwinrt_type(&f.typ)).collect();
    out.push_str(&format!("const _{}_Type = DynWinRtType.structType('{}', [{}]);\n",
        name, full_name, field_types.join(", ")));

    // _pack function: plain JS object → DynWinRtStruct
    out.push_str(&format!("function _pack{}(v: {}): DynWinRtStruct {{\n", name, name));
    out.push_str(&format!("    const s = DynWinRtStruct.create(_{}_Type);\n", name));
    for (i, f) in fields.iter().enumerate() {
        out.push_str(&format!("    {};\n", struct_field_setter(&f.typ, i, &format!("v.{}", to_camel_case(&f.name)))));
    }
    out.push_str("    return s;\n");
    out.push_str("}\n");

    out
}

/// Generate a TypeScript file for a single RuntimeClass.
/// Uses `registerInterface` + `invoke` pattern.
pub fn generate_class(class: &ClassMeta, known_types: &HashSet<String>, delegate_type_names: &HashSet<String>) -> String {
    // Collect structs used in all method signatures (needed for import and helpers)
    let used_structs = collect_used_structs_from_class(class);
    let has_structs = !used_structs.is_empty();

    let mut out = String::new();

    // Header
    out.push_str("// Generated by winrt-meta — do not edit\n");
    if has_structs {
        out.push_str("import { DynWinRtType, DynWinRtMethodSig, DynWinRtValue, DynWinRtArray, DynWinRtStruct, DynWinRtDelegate, WinGuid } from 'dynwinrt-js';\n");
    } else {
        out.push_str("import { DynWinRtType, DynWinRtMethodSig, DynWinRtValue, DynWinRtArray, DynWinRtDelegate, WinGuid } from 'dynwinrt-js';\n");
    }

    // Collect delegate names from all interfaces of this class
    let mut delegate_names: HashSet<String> = delegate_type_names.clone();
    let all_ifaces: Vec<&InterfaceMeta> = class.default_interface.iter()
        .chain(class.factory_interfaces.iter())
        .chain(class.static_interfaces.iter())
        .chain(class.required_interfaces.iter())
        .collect();
    for iface in &all_ifaces {
        for method in &iface.methods {
            for p in &method.params {
                match &p.typ {
                    TypeMeta::Delegate { name, .. } => { delegate_names.insert(name.clone()); }
                    _ => {}
                }
                if method.is_event_add || method.is_event_remove || method.name.starts_with("put_") {
                    if let TypeMeta::Parameterized { name, args, .. } = &p.typ {
                        delegate_names.insert(crate::meta::make_parameterized_name(name, args));
                    }
                }
            }
        }
    }

    // Collection generics import (skip delegates)
    let collection_names = collect_used_generics_from_class(class);
    for cname in &collection_names {
        if !delegate_names.contains(cname) {
            out.push_str(&format!("import {{ {} }} from './{}';\n", cname, cname));
        }
    }

    // Import delegate IID + PARAM_TYPES for event methods
    for dname in &delegate_names {
        out.push_str(&format!(
            "import {{ IID_{dname}, {dname}_PARAM_TYPES }} from './{dname}';\n",
        ));
    }

    // Type imports — only for types that have generated .ts files (skip delegates)
    let imports = collect_type_imports(class);
    for (_ns, name, kind) in &imports {
        if known_types.contains(name) && !delegate_names.contains(name) {
            out.push_str(&format_type_import(name, kind));
        }
    }
    out.push('\n');

    // IID constants for all interfaces used by this class
    if let Some(ref iface) = class.default_interface {
        if !iface.iid.is_empty() {
            out.push_str(&format!(
                "const IID_{} = WinGuid.parse('{}');\n",
                iface.name, iface.iid
            ));
        }
    }
    for iface in &class.factory_interfaces {
        if !iface.iid.is_empty() {
            out.push_str(&format!(
                "const IID_{} = WinGuid.parse('{}');\n",
                iface.name, iface.iid
            ));
        }
    }
    for iface in &class.static_interfaces {
        if !iface.iid.is_empty() {
            out.push_str(&format!(
                "const IID_{} = WinGuid.parse('{}');\n",
                iface.name, iface.iid
            ));
        }
    }
    for iface in &class.required_interfaces {
        if !iface.iid.is_empty() {
            out.push_str(&format!(
                "const IID_{} = WinGuid.parse('{}');\n",
                iface.name, iface.iid
            ));
        }
    }
    out.push('\n');

    // Interface registrations (exclusive interfaces used by this class)
    if let Some(ref iface) = class.default_interface {
        out.push_str(&generate_interface_registration(iface));
        out.push('\n');
    }
    for iface in &class.factory_interfaces {
        out.push_str(&generate_interface_registration(iface));
        out.push('\n');
    }
    for iface in &class.static_interfaces {
        out.push_str(&generate_interface_registration(iface));
        out.push('\n');
    }
    for iface in &class.required_interfaces {
        // Use _ prefix for registration variable to avoid shadowing the exported wrapper class
        let mut reg = generate_interface_registration(iface);
        reg = reg.replacen(&format!("const {} =", iface.name), &format!("const _{} =", iface.name), 1);
        out.push_str(&reg);
        out.push('\n');
    }

    // Struct interface + unpack/pack helpers
    for s in &used_structs {
        out.push_str(&generate_struct_helpers(s));
        out.push('\n');
    }

    // Class declaration
    out.push_str(&format!("export class {} {{\n", class.name));
    out.push_str("    readonly _obj: DynWinRtValue;\n\n");
    out.push_str("    constructor(obj: DynWinRtValue) {\n");
    out.push_str("        this._obj = obj;\n");
    out.push_str("    }\n");

    // Default constructor
    if class.has_default_constructor {
        let has_create_factory = class.factory_interfaces.iter()
            .any(|iface| iface.methods.iter().any(|m| {
                let camel = to_camel_case(&m.name);
                camel == "create" || camel.starts_with("create")
            }));
        let ctor_name = if has_create_factory { "createDefault" } else { "create" };
        out.push('\n');
        out.push_str(&format!(
            "    static {}(): {} {{\n",
            ctor_name, class.name
        ));
        // activationFactory returns IActivationFactory; call ActivateInstance (vtable 6) to get instance
        out.push_str(&format!(
            "        return new {}(DynWinRtValue.activationFactory('{}').call(6, DynWinRtType.object(), [], []));\n",
            class.name, class.full_name
        ));
        out.push_str("    }\n");
    }

    // Factory methods
    for iface in &class.factory_interfaces {
        for method in &iface.methods {
            out.push('\n');
            out.push_str(&generate_factory_method_invoke(class, iface, method, known_types));
        }
    }

    // Static methods
    for iface in &class.static_interfaces {
        for method in &iface.methods {
            out.push('\n');
            out.push_str(&generate_static_method_invoke(class, iface, method, known_types));
        }
    }

    // Instance methods: only default interface methods go directly on the class.
    // Non-default interface methods are accessed via .as(InterfaceWrapper).
    if let Some(ref default_iface) = class.default_interface {
        let iface_var = default_iface.name.clone();
        for method in &default_iface.methods {
            out.push('\n');
            out.push_str(&generate_iface_instance_method(default_iface, &iface_var, method, known_types, &delegate_type_names));
        }
    }

    // .as() method for accessing non-default interfaces
    // Uses static from() which does QI cast internally
    if !class.required_interfaces.is_empty() {
        out.push('\n');
        out.push_str("    as<T>(InterfaceClass: { from(obj: DynWinRtValue): T }): T {\n");
        out.push_str("        return InterfaceClass.from(this._obj);\n");
        out.push_str("    }\n");
    }

    out.push_str("}\n");

    // Generate inline wrapper classes for required interfaces (non-default)
    // so they can be used with .as()
    // Registration variable uses _ prefix to avoid shadowing the exported class name.
    for req_iface in &class.required_interfaces {
        if req_iface.iid.is_empty() { continue; }
        let reg_var = format!("_{}", req_iface.name);
        out.push('\n');
        out.push_str(&format!("export class {} {{\n", req_iface.name));
        out.push_str("    readonly _obj: DynWinRtValue;\n\n");
        out.push_str("    constructor(obj: DynWinRtValue) {\n");
        out.push_str("        this._obj = obj;\n");
        out.push_str("    }\n\n");
        out.push_str(&format!(
            "    static from(obj: DynWinRtValue): {} {{\n",
            req_iface.name
        ));
        out.push_str(&format!(
            "        return new {}(obj.cast(IID_{}));\n",
            req_iface.name, req_iface.name
        ));
        out.push_str("    }\n");
        for method in &req_iface.methods {
            out.push('\n');
            out.push_str(&generate_iface_instance_method(req_iface, &reg_var, method, known_types, &delegate_type_names));
        }
        out.push_str("}\n");
    }
    out
}

// ======================================================================
// Interface registration helper
// ======================================================================

fn generate_interface_registration(iface: &InterfaceMeta) -> String {
    let mut out = String::new();
    out.push_str(&format!("const {} = DynWinRtType.registerInterface(\n", iface.name));
    out.push_str(&format!("    \"{}\", IID_{})\n", iface.name, iface.name));
    for method in &iface.methods {
        out.push_str(&format!(
            "    .addMethod(\"{}\", {})\n",
            method.name,
            build_method_sig(method)
        ));
    }
    trim_trailing_newline_add_semicolon(&mut out);
    out
}

fn trim_trailing_newline_add_semicolon(out: &mut String) {
    if out.ends_with(")\n") {
        out.truncate(out.len() - 1);
        out.push_str(";\n");
    }
}

// ======================================================================
// Method signature builder
// ======================================================================

/// Build a `new DynWinRtMethodSig().addIn(...)...addOut(...)` expression.
fn build_method_sig(method: &MethodMeta) -> String {
    let mut parts = Vec::new();

    // In params
    for param in &method.params {
        if param.direction == ParamDirection::In {
            parts.push(format!(".addIn({})", ts_dynwinrt_type(&param.typ)));
        }
    }

    // Out params (explicit [out] parameters in method signature)
    for param in &method.params {
        if param.direction == ParamDirection::Out {
            parts.push(format!(".addOut({})", ts_dynwinrt_type(&param.typ)));
        } else if param.direction == ParamDirection::OutFill {
            parts.push(format!(".addOutFill({})", ts_dynwinrt_type(&param.typ)));
        }
    }

    // Return type (WinRT return value = [out, retval])
    if let Some(ref return_type) = method.return_type {
        parts.push(format!(".addOut({})", ts_dynwinrt_type(return_type)));
    }

    if parts.is_empty() {
        "new DynWinRtMethodSig()".to_string()
    } else {
        format!("new DynWinRtMethodSig(){}", parts.join(""))
    }
}

// ======================================================================
// Type expression: recursive expansion
// ======================================================================

/// Map a TypeMeta to a fully-expanded `DynWinRtType.*()` expression.
/// Recursively expands all compound types to leaf primitives.
fn ts_dynwinrt_type(typ: &TypeMeta) -> String {
    match typ {
        // Primitives
        TypeMeta::Bool => "DynWinRtType.boolType()".to_string(),
        TypeMeta::I8 => "DynWinRtType.i8Type()".to_string(),
        TypeMeta::I16 => "DynWinRtType.i16()".to_string(),
        TypeMeta::Char16 => "DynWinRtType.u16()".to_string(),
        TypeMeta::I32 => "DynWinRtType.i32()".to_string(),
        TypeMeta::U8 => "DynWinRtType.u8()".to_string(),
        TypeMeta::U16 => "DynWinRtType.u16()".to_string(),
        TypeMeta::U32 => "DynWinRtType.u32()".to_string(),
        TypeMeta::I64 => "DynWinRtType.i64()".to_string(),
        TypeMeta::U64 => "DynWinRtType.u64()".to_string(),
        TypeMeta::F32 => "DynWinRtType.f32()".to_string(),
        TypeMeta::F64 => "DynWinRtType.f64()".to_string(),

        // Strings
        TypeMeta::String => "DynWinRtType.hstring()".to_string(),

        // GUID — native type in dynwinrt
        TypeMeta::Guid => "DynWinRtType.guidType()".to_string(),

        // Generic object
        TypeMeta::Object => "DynWinRtType.object()".to_string(),

        // Interface — use interface(IID) if available
        TypeMeta::Interface { iid, .. } if !iid.is_empty() => {
            format!("DynWinRtType.interface(WinGuid.parse('{}'))", iid)
        }
        TypeMeta::Interface { .. } => "DynWinRtType.object()".to_string(),

        // RuntimeClass — runtimeClass(fullName, defaultIID)
        TypeMeta::RuntimeClass { namespace, name, default_iid } => {
            let full_name = format!("{}.{}", namespace, name);
            if !default_iid.is_empty() {
                format!(
                    "DynWinRtType.runtimeClass('{}', WinGuid.parse('{}'))",
                    full_name, default_iid
                )
            } else {
                "DynWinRtType.object()".to_string()
            }
        }

        // Delegate — COM pointer
        TypeMeta::Delegate { .. } => "DynWinRtType.object()".to_string(),

        // Async patterns — recursively expand inner types
        TypeMeta::AsyncOperation(inner) => {
            format!("DynWinRtType.iAsyncOperation({})", ts_dynwinrt_type(inner))
        }
        TypeMeta::AsyncOperationWithProgress(result, progress) => {
            format!("DynWinRtType.iAsyncOperationWithProgress({}, {})",
                ts_dynwinrt_type(result), ts_dynwinrt_type(progress))
        }
        TypeMeta::AsyncAction => {
            "DynWinRtType.iAsyncAction()".to_string()
        }
        TypeMeta::AsyncActionWithProgress(progress) => {
            format!("DynWinRtType.iAsyncActionWithProgress({})", ts_dynwinrt_type(progress))
        }

        // Struct — named for correct IID signature, recursively expand fields
        TypeMeta::Struct { namespace, name, fields } => {
            let full_name = format!("{}.{}", namespace, name);
            let field_types: Vec<String> = fields.iter()
                .map(|f| ts_dynwinrt_type(&f.typ))
                .collect();
            format!("DynWinRtType.structType('{}', [{}])", full_name, field_types.join(", "))
        }

        // Array — recursively expand element type
        TypeMeta::Array(inner) => {
            format!("DynWinRtType.arrayType({})", ts_dynwinrt_type(inner))
        }

        // Enum — named for correct IID signature, with member values
        TypeMeta::Enum { namespace, name, members, .. } => {
            let full_name = format!("{}.{}", namespace, name);
            if members.is_empty() {
                format!("DynWinRtType.enumType('{}')", full_name)
            } else {
                let names: Vec<String> = members.iter().map(|m| format!("'{}'", m.name)).collect();
                let values: Vec<String> = members.iter().map(|m| m.value.to_string()).collect();
                format!("DynWinRtType.enumType('{}', [{}], [{}])",
                    full_name, names.join(", "), values.join(", "))
            }
        }

        // Parameterized — preserve generic type info for IID computation
        TypeMeta::Parameterized { piid, args, .. } => {
            if piid.is_empty() {
                "DynWinRtType.object()".to_string()
            } else {
                let arg_types: Vec<String> = args.iter().map(|a| ts_dynwinrt_type(a)).collect();
                format!("DynWinRtType.parameterized(WinGuid.parse('{}'), [{}])", piid, arg_types.join(", "))
            }
        }
    }
}

// ======================================================================
// Method generation — invoke pattern
// ======================================================================

fn generate_factory_method_invoke(
    class: &ClassMeta,
    iface: &InterfaceMeta,
    method: &MethodMeta,
    known_types: &HashSet<String>,
) -> String {
    let in_params = get_in_params(method);
    let ts_params = ts_param_list(&in_params, known_types);

    let is_async = method.return_type.as_ref().is_some_and(|rt| rt.is_async());
    let return_ts_type = if is_async {
        format!("Promise<{}>", class.name)
    } else {
        class.name.clone()
    };

    let mut out = String::new();
    let async_kw = if is_async { "async " } else { "" };
    out.push_str(&format!(
        "    static {}{}({}): {} {{\n",
        async_kw, to_camel_case(&method.name), ts_params, return_ts_type
    ));

    // Get factory, cast to interface
    out.push_str(&format!(
        "        const factory = DynWinRtValue.activationFactory('{}')\n",
        class.full_name
    ));
    out.push_str(&format!(
        "            .cast(IID_{});\n",
        iface.name
    ));

    // Invoke
    let args_expr = build_args_expr(&in_params);
    let invoke_expr = format!(
        "{}.method({}).invoke(factory, [{}])",
        iface.name, method.vtable_index, args_expr
    );

    if is_async {
        out.push_str(&format!(
            "        return new {}(await {}.toPromise());\n",
            class.name, invoke_expr
        ));
    } else {
        out.push_str(&format!(
            "        return new {}({});\n",
            class.name, invoke_expr
        ));
    }
    out.push_str("    }\n");
    out
}

fn generate_static_method_invoke(
    class: &ClassMeta,
    iface: &InterfaceMeta,
    method: &MethodMeta,
    known_types: &HashSet<String>,
) -> String {
    let in_params = get_in_params(method);
    let ts_params = ts_param_list(&in_params, known_types);

    let return_type = method.return_type.as_ref();
    let is_async = return_type.is_some_and(|rt| rt.is_async());
    let ts_return = ts_return_type_safe(return_type, is_async, known_types);

    let mut out = String::new();

    // Static property getter
    if method.is_property_getter && in_params.is_empty() {
        let prop_name = to_camel_case(method.name.strip_prefix("get_").unwrap_or(&method.name));
        out.push_str(&format!("    static get {}(): {} {{\n", prop_name, ts_return));
        out.push_str(&format!(
            "        const statics = DynWinRtValue.activationFactory('{}')\n",
            class.full_name
        ));
        out.push_str(&format!(
            "            .cast(IID_{});\n",
            iface.name
        ));
        let invoke_expr = format!(
            "{}.method({}).invoke(statics, [])",
            iface.name, method.vtable_index
        );
        let converted = convert_return(&invoke_expr, return_type, false, known_types);
        out.push_str(&format!("        return {};\n", converted));
        out.push_str("    }\n");
    } else {
        let async_kw = if is_async { "async " } else { "" };
        out.push_str(&format!(
            "    static {}{}({}): {} {{\n",
            async_kw, to_camel_case(&method.name), ts_params, ts_return
        ));
        out.push_str(&format!(
            "        const statics = DynWinRtValue.activationFactory('{}')\n",
            class.full_name
        ));
        out.push_str(&format!(
            "            .cast(IID_{});\n",
            iface.name
        ));
        let args_expr = build_args_expr(&in_params);
        let invoke_expr = format!(
            "{}.method({}).invoke(statics, [{}])",
            iface.name, method.vtable_index, args_expr
        );
        let converted = convert_return(&invoke_expr, return_type, is_async, known_types);
        out.push_str(&format!("        return {};\n", converted));
        out.push_str("    }\n");
    }
    out
}

/// Generate an instance method for an interface wrapper class.
/// Uses `_InterfaceName` as the registered interface variable and `this._obj` directly.
fn generate_iface_instance_method(
    _iface: &InterfaceMeta,
    iface_var: &str,
    method: &MethodMeta,
    known_types: &HashSet<String>,
    delegate_type_names: &HashSet<String>,
) -> String {
    generate_method_body(iface_var, "this._obj", method, known_types, delegate_type_names, None)
}

fn generate_instance_method_invoke(
    default_iface: &InterfaceMeta,
    method: &MethodMeta,
    known_types: &HashSet<String>,
    delegate_type_names: &HashSet<String>,
    ts_name_override: Option<&str>,
) -> String {
    let cast_expr = if !default_iface.iid.is_empty() {
        format!("this._obj.cast(IID_{})", default_iface.name)
    } else {
        "this._obj".to_string()
    };
    generate_method_body(&default_iface.name, &cast_expr, method, known_types, delegate_type_names, ts_name_override)
}

fn generate_method_body(
    iface_var: &str,
    obj_expr: &str,
    method: &MethodMeta,
    known_types: &HashSet<String>,
    delegate_type_names: &HashSet<String>,
    ts_name_override: Option<&str>,
) -> String {
    let in_params = get_in_params(method);
    let return_type = method.return_type.as_ref();
    let is_async = return_type.is_some_and(|rt| rt.is_async());
    // Methods with array out params (ReceiveArray/FillArray) return the array even without retval
    let has_array_out = method.params.iter().any(|p| {
        (p.direction == ParamDirection::Out || p.direction == ParamDirection::OutFill)
            && matches!(p.typ, TypeMeta::Array(_))
    });
    let has_return = return_type.is_some() || has_array_out;

    let mut out = String::new();

    // Event add: create delegate from JS callback, call add_, return token
    if method.is_event_add {
        let event_name = to_camel_case(method.name.strip_prefix("add_").unwrap_or(&method.name));
        // Get delegate name for IID and param types
        let delegate_name = in_params.first().and_then(|p| match &p.typ {
            TypeMeta::Parameterized { name, args, .. } =>
                Some(crate::meta::make_parameterized_name(name, args)),
            TypeMeta::Delegate { name, .. } => Some(name.clone()),
            _ => None,
        });
        out.push_str(&format!(
            "    on{}(callback: (...args: DynWinRtValue[]) => void): DynWinRtValue {{\n",
            capitalize(&event_name)
        ));
        if let Some(ref dname) = delegate_name {
            out.push_str(&format!(
                "        const handler = DynWinRtDelegate.create(IID_{}, {}_PARAM_TYPES, callback);\n",
                dname, dname
            ));
        } else {
            // Fallback: unknown delegate type, use object IID (may not work at runtime)
            out.push_str(
                "        const handler = DynWinRtDelegate.create(DynWinRtType.object().iid()!, [DynWinRtType.object(), DynWinRtType.object()], callback);\n"
            );
        }
        out.push_str(&format!(
            "        return {}.method({}).invoke({}, [handler.toValue()]);\n",
            iface_var, method.vtable_index, obj_expr
        ));
        out.push_str("    }\n");
        return out;
    }
    // Event remove: pass token to remove_
    if method.is_event_remove {
        let event_name = to_camel_case(method.name.strip_prefix("remove_").unwrap_or(&method.name));
        out.push_str(&format!(
            "    off{}(token: DynWinRtValue): void {{\n",
            capitalize(&event_name)
        ));
        out.push_str(&format!(
            "        {}.method({}).invoke({}, [token]);\n",
            iface_var, method.vtable_index, obj_expr
        ));
        out.push_str("    }\n");
        return out;
    }

    // Helper: check if a type refers to a delegate (needs DynWinRtValue, not class name)
    let is_delegate_type = |typ: Option<&TypeMeta>| -> bool {
        match typ {
            Some(TypeMeta::Delegate { .. }) => true,
            Some(TypeMeta::Interface { name, .. }) => delegate_type_names.contains(name),
            _ => false,
        }
    };

    if method.is_property_getter && in_params.is_empty() {
        // Property getter
        let prop_name = to_camel_case(method.name.strip_prefix("get_").unwrap_or(&method.name));
        let ts_return = if is_delegate_type(return_type) {
            "DynWinRtValue".to_string()
        } else {
            ts_return_type_safe(return_type, false, known_types)
        };
        out.push_str(&format!("    get {}(): {} {{\n", prop_name, ts_return));
        let invoke_expr = format!(
            "{}.method({}).invoke({}, [])",
            iface_var, method.vtable_index, obj_expr
        );
        let converted = if is_delegate_type(return_type) {
            invoke_expr.clone()
        } else {
            convert_return(&invoke_expr, return_type, false, known_types)
        };
        out.push_str(&format!("        return {};\n", converted));
        out.push_str("    }\n");
    } else if method.is_property_setter {
        // Property setter
        let prop_name = to_camel_case(method.name.strip_prefix("put_").unwrap_or(&method.name));
        let param_type = if in_params.first().is_some_and(|p| is_delegate_type(Some(&p.typ))) {
            "DynWinRtValue".to_string()
        } else {
            in_params.first()
                .map(|p| ts_param_type_safe(&p.typ, known_types))
                .unwrap_or_else(|| "any".to_string())
        };
        out.push_str(&format!("    set {}(value: {}) {{\n", prop_name, param_type));
        let arg = in_params.first()
            .map(|p| wrap_arg("value", &p.typ))
            .unwrap_or_else(|| "value".to_string());
        out.push_str(&format!(
            "        {}.method({}).invoke({}, [{}]);\n",
            iface_var, method.vtable_index, obj_expr, arg
        ));
        out.push_str("    }\n");
    } else {
        // Regular method
        let ts_params = ts_param_list(&in_params, known_types);
        // For array out params, determine the element type for proper return type
        let array_out_elem = if has_array_out && return_type.is_none() {
            method.params.iter().find_map(|p| {
                if (p.direction == ParamDirection::Out || p.direction == ParamDirection::OutFill) {
                    if let TypeMeta::Array(inner) = &p.typ { Some(inner.as_ref()) } else { None }
                } else { None }
            })
        } else { None };
        let ts_return = if let Some(elem) = array_out_elem {
            ts_array_element_type(elem, known_types)
        } else {
            ts_return_type_safe(return_type, is_async, known_types)
        };
        let method_name = ts_name_override.map(|s| s.to_string()).unwrap_or_else(|| to_camel_case(&method.name));
        let async_kw = if is_async { "async " } else { "" };

        out.push_str(&format!(
            "    {}{}({}): {} {{\n",
            async_kw, method_name, ts_params, ts_return
        ));

        let args_expr = build_args_expr(&in_params);
        let invoke_expr = format!(
            "{}.method({}).invoke({}, [{}])",
            iface_var, method.vtable_index, obj_expr, args_expr
        );

        if !has_return && !is_async {
            out.push_str(&format!("        {};\n", invoke_expr));
        } else if let Some(elem) = array_out_elem {
            let arr_expr = format!("{}.asArray()", invoke_expr);
            let converted = convert_array_return(&arr_expr, elem, known_types);
            out.push_str(&format!("        return {};\n", converted));
        } else {
            let converted = convert_return(&invoke_expr, return_type, is_async, known_types);
            out.push_str(&format!("        return {};\n", converted));
        }
        out.push_str("    }\n");
    }

    out
}

// ======================================================================
// Helper: argument wrapping
// ======================================================================

fn build_args_expr(in_params: &[&crate::meta::ParamMeta]) -> String {
    in_params.iter()
        .map(|p| wrap_arg(&to_camel_case(&p.name), &p.typ))
        .collect::<Vec<_>>()
        .join(", ")
}

fn wrap_arg(name: &str, typ: &TypeMeta) -> String {
    match typ {
        TypeMeta::String => format!("DynWinRtValue.hstring({})", name),
        TypeMeta::Bool => format!("DynWinRtValue.boolValue({})", name),
        TypeMeta::I32 | TypeMeta::U32 | TypeMeta::Enum { .. }
        | TypeMeta::I8 | TypeMeta::U8 | TypeMeta::I16 | TypeMeta::U16
        | TypeMeta::Char16 => {
            format!("DynWinRtValue.i32({})", name)
        }
        TypeMeta::I64 | TypeMeta::U64 => format!("DynWinRtValue.i64({})", name),
        TypeMeta::F32 => format!("DynWinRtValue.f32({})", name),
        TypeMeta::F64 => format!("DynWinRtValue.f64({})", name),
        TypeMeta::Guid => format!("DynWinRtValue.guid(WinGuid.parse({}))", name),
        TypeMeta::RuntimeClass { .. } | TypeMeta::Object | TypeMeta::Interface { .. }
        | TypeMeta::Parameterized { .. } | TypeMeta::Delegate { .. } => {
            format!("({} as any)._obj ?? {}", name, name)
        }
        TypeMeta::Array(_) => format!("{}.toValue()", name),
        TypeMeta::Struct { name: struct_name, .. } if struct_name == "HResult" => {
            format!("DynWinRtValue.i32({})", name)
        }
        TypeMeta::Struct { name: struct_name, .. } => {
            format!("_pack{}({}).toValue()", struct_name, name)
        }
        _ => name.to_string(),
    }
}

// ======================================================================
// Helper: return conversion
// ======================================================================

/// Convert an array return expression to the appropriate JS array type.
fn convert_array_return(arr_expr: &str, inner: &TypeMeta, known_types: &HashSet<String>) -> String {
    match inner {
        TypeMeta::I8 => format!("{}.toI8Vec()", arr_expr),
        TypeMeta::U8 => format!("{}.toU8Vec()", arr_expr),
        TypeMeta::I16 => format!("{}.toI16Vec()", arr_expr),
        TypeMeta::U16 | TypeMeta::Char16 => format!("{}.toU16Vec()", arr_expr),
        TypeMeta::I32 | TypeMeta::Enum { .. } => format!("{}.toI32Vec()", arr_expr),
        TypeMeta::U32 => format!("{}.toU32Vec()", arr_expr),
        TypeMeta::I64 => format!("{}.toI64Vec()", arr_expr),
        TypeMeta::U64 => format!("{}.toU64Vec()", arr_expr),
        TypeMeta::F32 => format!("{}.toF32Vec()", arr_expr),
        TypeMeta::F64 => format!("{}.toF64Vec()", arr_expr),
        TypeMeta::Bool => format!("{}.toValues().map(v => v.toBool())", arr_expr),
        TypeMeta::String => format!("{}.toStringVec()", arr_expr),
        TypeMeta::Guid => format!("{}.toValues().map(v => v.toString())", arr_expr),
        TypeMeta::Struct { name, .. } if name == "HResult" => format!("{}.toI32Vec()", arr_expr),
        TypeMeta::Struct { name, .. } => format!("{}.toValues().map(v => _unpack{}(v))", arr_expr, name),
        TypeMeta::RuntimeClass { name, .. } if known_types.contains(name) => {
            format!("{}.toValues().map(v => new {}(v))", arr_expr, name)
        }
        TypeMeta::Interface { name, .. } if known_types.contains(name) => {
            format!("{}.toValues().map(v => new {}(v))", arr_expr, name)
        }
        _ => format!("{}.toValues()", arr_expr),
    }
}

/// TypeScript return type annotation for an array element type.
fn ts_array_element_type(inner: &TypeMeta, known_types: &HashSet<String>) -> String {
    match inner {
        TypeMeta::Bool => "boolean[]".to_string(),
        TypeMeta::String | TypeMeta::Guid => "string[]".to_string(),
        TypeMeta::I8 | TypeMeta::U8 | TypeMeta::I16 | TypeMeta::U16 | TypeMeta::Char16
        | TypeMeta::I32 | TypeMeta::U32 | TypeMeta::I64 | TypeMeta::U64
        | TypeMeta::F32 | TypeMeta::F64 | TypeMeta::Enum { .. } => "number[]".to_string(),
        TypeMeta::Struct { name, .. } if name == "HResult" => "number[]".to_string(),
        TypeMeta::Struct { name, .. } => format!("{}[]", name),
        TypeMeta::RuntimeClass { name, .. } if known_types.contains(name) => format!("{}[]", name),
        TypeMeta::Interface { name, .. } if known_types.contains(name) => format!("{}[]", name),
        _ => "DynWinRtValue[]".to_string(),
    }
}

fn convert_return(expr: &str, return_type: Option<&TypeMeta>, is_async: bool, known_types: &HashSet<String>) -> String {
    if is_async {
        let inner_type = match return_type {
            Some(TypeMeta::AsyncOperation(inner)) => Some(inner.as_ref()),
            Some(TypeMeta::AsyncOperationWithProgress(inner, _)) => Some(inner.as_ref()),
            _ => None,
        };
        let awaited = format!("(await {}.toPromise())", expr);
        return convert_return(&awaited, inner_type, false, known_types);
    }
    match return_type {
        Some(TypeMeta::String) | Some(TypeMeta::Guid) => format!("{}.toString()", expr),
        Some(TypeMeta::I8 | TypeMeta::U8 | TypeMeta::I16 | TypeMeta::U16 | TypeMeta::Char16
            | TypeMeta::I32 | TypeMeta::U32) => format!("{}.toNumber()", expr),
        Some(TypeMeta::I64 | TypeMeta::U64) => format!("{}.toI64()", expr),
        Some(TypeMeta::F32 | TypeMeta::F64) => format!("{}.toF64()", expr),
        Some(TypeMeta::Bool) => format!("{}.toBool()", expr),
        Some(TypeMeta::Enum { .. }) => format!("{}.toNumber()", expr),
        Some(TypeMeta::RuntimeClass { name, .. }) if known_types.contains(name) => {
            format!("new {}({})", name, expr)
        }
        Some(TypeMeta::Struct { name, .. }) if name == "HResult" => format!("{}.toNumber()", expr),
        Some(TypeMeta::Struct { name, .. }) => format!("_unpack{}({})", name, expr),
        Some(TypeMeta::Delegate { .. }) => expr.to_string(),
        Some(TypeMeta::Interface { name, .. }) if known_types.contains(name) => {
            format!("new {}({})", name, expr)
        }
        Some(TypeMeta::Parameterized { name, args, .. }) => {
            let concrete = crate::meta::make_parameterized_name(name, args);
            if known_types.contains(&concrete) {
                format!("new {}({})", concrete, expr)
            } else {
                expr.to_string()
            }
        }
        Some(TypeMeta::Array(inner)) => {
            let arr_expr = format!("{}.asArray()", expr);
            convert_array_return(&arr_expr, inner, known_types)
        }
        _ => expr.to_string(),
    }
}

// ======================================================================
// Helper: TypeScript type annotations
// ======================================================================

fn ts_param_type(typ: &TypeMeta) -> String {
    match typ {
        TypeMeta::Bool => "boolean".to_string(),
        TypeMeta::I8 | TypeMeta::U8 | TypeMeta::I16 | TypeMeta::U16 | TypeMeta::Char16
        | TypeMeta::I32 | TypeMeta::U32 | TypeMeta::I64 | TypeMeta::U64
        | TypeMeta::F32 | TypeMeta::F64 => {
            "number".to_string()
        }
        TypeMeta::String | TypeMeta::Guid => "string".to_string(),
        TypeMeta::RuntimeClass { name, .. }
        | TypeMeta::Enum { name, .. }
        | TypeMeta::Interface { name, .. } => name.clone(),
        TypeMeta::Parameterized { name, args, .. } => crate::meta::make_parameterized_name(name, args),
        TypeMeta::Array(_) => "DynWinRtArray".to_string(),
        TypeMeta::Object | TypeMeta::Delegate { .. } => "DynWinRtValue".to_string(),
        TypeMeta::Struct { name, .. } if name == "HResult" => "number".to_string(),
        TypeMeta::Struct { name, .. } => name.clone(),
        _ => "any".to_string(),
    }
}

fn ts_param_type_safe(typ: &TypeMeta, known: &HashSet<String>) -> String {
    match typ {
        TypeMeta::RuntimeClass { name, .. }
        | TypeMeta::Enum { name, .. }
        | TypeMeta::Interface { name, .. } if !known.contains(name) => "DynWinRtValue".to_string(),
        _ => ts_param_type(typ),
    }
}

fn ts_return_type_safe(typ: Option<&TypeMeta>, is_async: bool, known: &HashSet<String>) -> String {
    match typ {
        Some(TypeMeta::RuntimeClass { name, .. })
        | Some(TypeMeta::Enum { name, .. })
        | Some(TypeMeta::Interface { name, .. }) if !known.contains(name) => {
            if is_async { "Promise<DynWinRtValue>".to_string() } else { "DynWinRtValue".to_string() }
        }
        Some(TypeMeta::AsyncOperation(inner)) => {
            format!("Promise<{}>", ts_return_type_safe(Some(inner), false, known))
        }
        Some(TypeMeta::AsyncOperationWithProgress(result, _)) => {
            format!("Promise<{}>", ts_return_type_safe(Some(result), false, known))
        }
        Some(TypeMeta::Array(inner)) => {
            let s = ts_array_element_type(inner, known);
            if is_async { format!("Promise<{}>", s) } else { s }
        }
        _ => ts_return_type(typ, is_async),
    }
}

fn ts_return_type(typ: Option<&TypeMeta>, is_async: bool) -> String {
    let inner = match typ {
        Some(TypeMeta::String) | Some(TypeMeta::Guid) => "string",
        Some(TypeMeta::Bool) => "boolean",
        Some(TypeMeta::I8 | TypeMeta::U8 | TypeMeta::I16 | TypeMeta::U16 | TypeMeta::Char16
            | TypeMeta::I32 | TypeMeta::U32 | TypeMeta::I64 | TypeMeta::U64
            | TypeMeta::F32 | TypeMeta::F64) => "number",
        Some(TypeMeta::RuntimeClass { name, .. }) => {
            return if is_async { format!("Promise<{}>", name) } else { name.clone() }
        }
        Some(TypeMeta::Enum { name, .. }) => {
            return if is_async { format!("Promise<{}>", name) } else { name.clone() }
        }
        Some(TypeMeta::Interface { name, .. }) => {
            return if is_async { format!("Promise<{}>", name) } else { name.clone() }
        }
        Some(TypeMeta::Parameterized { name, args, .. }) => {
            let s = crate::meta::make_parameterized_name(name, args);
            return if is_async { format!("Promise<{}>", s) } else { s };
        }
        Some(TypeMeta::AsyncOperation(inner)) => {
            return format!("Promise<{}>", ts_return_type(Some(inner), false));
        }
        Some(TypeMeta::AsyncOperationWithProgress(result, _)) => {
            return format!("Promise<{}>", ts_return_type(Some(result), false));
        }
        Some(TypeMeta::AsyncAction) => return "Promise<void>".to_string(),
        Some(TypeMeta::AsyncActionWithProgress(_)) => return "Promise<void>".to_string(),
        Some(TypeMeta::Array(inner)) => {
            let s = ts_array_element_type(inner, &HashSet::new());
            return if is_async { format!("Promise<{}>", s) } else { s };
        }
        Some(TypeMeta::Object) | Some(TypeMeta::Delegate { .. }) => "DynWinRtValue",
        Some(TypeMeta::Struct { name, .. }) if name == "HResult" => "number",
        Some(TypeMeta::Struct { name, .. }) => {
            return if is_async { format!("Promise<{}>", name) } else { name.clone() }
        }
        None => "void",
        _ => "any",
    };
    if is_async { format!("Promise<{}>", inner) } else { inner.to_string() }
}

// ======================================================================
// Helpers: parameter lists, camelCase, imports
// ======================================================================

/// Collect the set of known generic collection names used in method signatures.
/// Returns e.g. ["IVectorView", "IMap"] for import generation.
fn collect_used_generics_from_methods(methods: &[MethodMeta]) -> Vec<String> {
    let mut names: HashSet<String> = HashSet::new();
    fn visit(typ: &TypeMeta, names: &mut HashSet<String>) {
        match typ {
            TypeMeta::Parameterized { name, args, .. } => {
                names.insert(crate::meta::make_parameterized_name(name, args));
                for arg in args { visit(arg, names); }
            }
            TypeMeta::AsyncOperation(inner) | TypeMeta::AsyncActionWithProgress(inner) => visit(inner, names),
            TypeMeta::AsyncOperationWithProgress(r, p) => { visit(r, names); visit(p, names); }
            TypeMeta::Array(inner) => visit(inner, names),
            _ => {}
        }
    }
    for m in methods {
        for p in &m.params { visit(&p.typ, &mut names); }
        if let Some(ref rt) = m.return_type { visit(rt, &mut names); }
    }
    let mut sorted: Vec<String> = names.into_iter().collect();
    sorted.sort();
    sorted
}

/// Collect all used generic names from a class (all its interfaces).
fn collect_used_generics_from_class(class: &ClassMeta) -> Vec<String> {
    let mut all_methods: Vec<&MethodMeta> = Vec::new();
    if let Some(ref iface) = class.default_interface {
        all_methods.extend(&iface.methods);
    }
    for iface in &class.factory_interfaces { all_methods.extend(&iface.methods); }
    for iface in &class.static_interfaces { all_methods.extend(&iface.methods); }
    for iface in &class.required_interfaces { all_methods.extend(&iface.methods); }

    let mut names: HashSet<String> = HashSet::new();
    fn visit2(typ: &TypeMeta, names: &mut HashSet<String>) {
        match typ {
            TypeMeta::Parameterized { name, args, .. } => {
                names.insert(crate::meta::make_parameterized_name(name, args));
                for arg in args { visit2(arg, names); }
            }
            TypeMeta::AsyncOperation(inner) | TypeMeta::AsyncActionWithProgress(inner) => visit2(inner, names),
            TypeMeta::AsyncOperationWithProgress(r, p) => { visit2(r, names); visit2(p, names); }
            TypeMeta::Array(inner) => visit2(inner, names),
            _ => {}
        }
    }
    for m in &all_methods {
        for p in &m.params { visit2(&p.typ, &mut names); }
        if let Some(ref rt) = m.return_type { visit2(rt, &mut names); }
    }
    let mut sorted: Vec<String> = names.into_iter().collect();
    sorted.sort();
    sorted
}

/// Format an import line based on type kind.
/// - Interfaces export both IID and wrapper class
/// - Classes and enums only export the name (IIDs are internal)
fn format_type_import(name: &str, kind: &str) -> String {
    if kind == "interface" {
        format!("import {{ IID_{name}, {name} }} from './{name}';\n")
    } else {
        format!("import {{ {} }} from './{}';\n", name, name)
    }
}

/// Collect type references from an interface for import generation.
/// Returns (namespace, name, kind) triples.
fn collect_iface_type_imports(iface: &InterfaceMeta) -> HashSet<(String, String, String)> {
    let mut imports: HashSet<(String, String, String)> = HashSet::new();
    let self_name = &iface.name;

    fn visit_type(typ: &TypeMeta, self_name: &str, imports: &mut HashSet<(String, String, String)>) {
        match typ {
            TypeMeta::RuntimeClass { namespace, name, .. } if name != self_name => {
                imports.insert((namespace.clone(), name.clone(), "class".into()));
            }
            TypeMeta::Interface { namespace, name, .. } if name != self_name => {
                imports.insert((namespace.clone(), name.clone(), "interface".into()));
            }
            TypeMeta::Enum { namespace, name, .. } => {
                imports.insert((namespace.clone(), name.clone(), "enum".into()));
            }
            TypeMeta::AsyncOperation(inner) | TypeMeta::AsyncActionWithProgress(inner) => {
                visit_type(inner, self_name, imports);
            }
            TypeMeta::AsyncOperationWithProgress(result, progress) => {
                visit_type(result, self_name, imports);
                visit_type(progress, self_name, imports);
            }
            TypeMeta::Struct { fields, .. } => {
                for f in fields { visit_type(&f.typ, self_name, imports); }
            }
            TypeMeta::Array(inner) => visit_type(inner, self_name, imports),
            TypeMeta::Parameterized { args, .. } => {
                for arg in args { visit_type(arg, self_name, imports); }
            }
            _ => {}
        }
    }

    for m in &iface.methods {
        for p in &m.params { visit_type(&p.typ, self_name, &mut imports); }
        if let Some(ref rt) = m.return_type { visit_type(rt, self_name, &mut imports); }
    }
    imports
}

fn get_in_params(method: &MethodMeta) -> Vec<&crate::meta::ParamMeta> {
    method.params.iter().filter(|p| p.direction == ParamDirection::In).collect()
}

fn ts_param_list(in_params: &[&crate::meta::ParamMeta], known_types: &HashSet<String>) -> String {
    in_params.iter()
        .map(|p| format!("{}: {}", to_camel_case(&p.name), ts_param_type_safe(&p.typ, known_types)))
        .collect::<Vec<_>>()
        .join(", ")
}

/// Collect type references from a class for import generation.
/// Returns (namespace, name, kind) triples.
pub fn collect_type_imports(class: &ClassMeta) -> HashSet<(String, String, String)> {
    let mut imports: HashSet<(String, String, String)> = HashSet::new();
    let class_name = &class.name;

    fn visit_type(typ: &TypeMeta, class_name: &str, imports: &mut HashSet<(String, String, String)>) {
        match typ {
            TypeMeta::RuntimeClass { namespace, name, .. } if name != class_name => {
                imports.insert((namespace.clone(), name.clone(), "class".into()));
            }
            TypeMeta::Interface { namespace, name, .. } => {
                imports.insert((namespace.clone(), name.clone(), "interface".into()));
            }
            TypeMeta::Enum { namespace, name, .. } => {
                imports.insert((namespace.clone(), name.clone(), "enum".into()));
            }
            TypeMeta::AsyncOperation(inner) | TypeMeta::AsyncActionWithProgress(inner) => {
                visit_type(inner, class_name, imports);
            }
            TypeMeta::AsyncOperationWithProgress(result, progress) => {
                visit_type(result, class_name, imports);
                visit_type(progress, class_name, imports);
            }
            TypeMeta::Struct { fields, .. } => {
                for f in fields {
                    visit_type(&f.typ, class_name, imports);
                }
            }
            TypeMeta::Array(inner) => {
                visit_type(inner, class_name, imports);
            }
            TypeMeta::Parameterized { args, .. } => {
                for arg in args { visit_type(arg, class_name, imports); }
            }
            _ => {}
        }
    }

    fn visit_methods(methods: &[MethodMeta], class_name: &str, imports: &mut HashSet<(String, String, String)>) {
        for m in methods {
            for p in &m.params {
                visit_type(&p.typ, class_name, imports);
            }
            if let Some(ref rt) = m.return_type {
                visit_type(rt, class_name, imports);
            }
        }
    }

    if let Some(ref iface) = class.default_interface {
        visit_methods(&iface.methods, class_name, &mut imports);
    }
    for iface in &class.factory_interfaces {
        visit_methods(&iface.methods, class_name, &mut imports);
    }
    for iface in &class.static_interfaces {
        visit_methods(&iface.methods, class_name, &mut imports);
    }
    for iface in &class.required_interfaces {
        visit_methods(&iface.methods, class_name, &mut imports);
    }

    imports
}

fn strip_generic_arity(name: &str) -> &str {
    name.split('`').next().unwrap_or(name)
}

fn to_camel_case(s: &str) -> String {
    if s.is_empty() {
        return String::new();
    }
    let mut chars = s.chars();
    let first = chars.next().unwrap().to_lowercase().to_string();
    format!("{}{}", first, chars.collect::<String>())
}

fn capitalize(s: &str) -> String {
    if s.is_empty() { return String::new(); }
    let mut chars = s.chars();
    let first = chars.next().unwrap().to_uppercase().to_string();
    format!("{}{}", first, chars.collect::<String>())
}
